"""
Build the 2025-26 Bowman Basketball checklist JSON.

Output schema:
{
  "set": { meta },
  "parallelLibrary": { id: { name, printRun, exclusivity } },
  "subsets": [
    {
      "id", "name", "cardPrefix", "cardCount", "type", "isAuto", "isInsert",
      "parallels": [parallelId, ...],
      "cards": [ { number, player, team, isRC } ]
    }
  ]
}

A "trackable variant" = one card x one parallel (or the base/no-parallel version).
The app expands these at runtime — we don't enumerate every variant in the seed file.
"""

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Parallel library — every distinct parallel referenced anywhere in the set.
# Same parallel can apply to multiple subsets; defined once here.
# ---------------------------------------------------------------------------

PARALLELS = {
    # Paper border parallels (Base / Prospects / Paper retail autos)
    "paper-purple-pattern":       {"name": "Purple Pattern Border",       "printRun": 199,  "exclusive": None},
    "paper-pink":                 {"name": "Pink Border",                 "printRun": 175,  "exclusive": None},
    "paper-blue":                 {"name": "Blue Border",                 "printRun": 150,  "exclusive": None},
    "paper-green":                {"name": "Green Border",                "printRun": 99,   "exclusive": "Retail"},
    "paper-green-pattern":        {"name": "Green Pattern Border",        "printRun": 99,   "exclusive": "Retail"},
    "paper-yellow":               {"name": "Yellow Border",               "printRun": 75,   "exclusive": None},
    "paper-gold":                 {"name": "Gold Border",                 "printRun": 50,   "exclusive": None},
    "paper-orange":               {"name": "Orange Border",               "printRun": 25,   "exclusive": "Hobby"},
    "paper-black":                {"name": "Black Border",                "printRun": 10,   "exclusive": "Hobby"},
    "paper-black-pattern":        {"name": "Black Pattern Border",        "printRun": 10,   "exclusive": "Hobby"},
    "paper-red":                  {"name": "Red Border",                  "printRun": 5,    "exclusive": None},
    "paper-platinum":             {"name": "Platinum Border (Rainbow Foil)", "printRun": 1, "exclusive": None},

    # Chrome refractor parallels
    "chrome-geometric":           {"name": "Geometric",                   "printRun": None, "exclusive": "Breaker"},
    "chrome-mojo":                {"name": "Mojo Refractor",              "printRun": None, "exclusive": "Mega"},
    "chrome-reptilian":           {"name": "Reptilian Refractor",         "printRun": None, "exclusive": None},
    "chrome-mini-diamond":        {"name": "Mini-Diamond Refractor",      "printRun": None, "exclusive": "Hobby"},
    "chrome-refractor":           {"name": "Refractor",                   "printRun": 499,  "exclusive": None},
    "chrome-lava":                {"name": "Lava Refractor",              "printRun": 399,  "exclusive": "Retail"},
    "chrome-fuchsia-mojo":        {"name": "Fuchsia Mojo",                "printRun": 299,  "exclusive": "Mega"},
    "chrome-speckle":             {"name": "Speckle Refractor",           "printRun": 299,  "exclusive": None},
    "chrome-burgundy-mojo":       {"name": "Burgundy Mojo",               "printRun": 275,  "exclusive": "Mega"},
    "chrome-purple":              {"name": "Purple Refractor",            "printRun": 250,  "exclusive": None},
    "chrome-purple-mojo":         {"name": "Purple Mojo",                 "printRun": 250,  "exclusive": "Mega"},
    "chrome-fuchsia":             {"name": "Fuchsia Refractor",           "printRun": 199,  "exclusive": None},
    "chrome-reptilian-fuchsia":   {"name": "Reptilian Fuchsia Refractor", "printRun": 199,  "exclusive": None},
    "chrome-pink-mojo":           {"name": "Pink Mojo",                   "printRun": 199,  "exclusive": "Mega"},
    "chrome-navy-mojo":           {"name": "Navy Mojo",                   "printRun": 175,  "exclusive": "Mega"},
    "chrome-blue":                {"name": "Blue Refractor",              "printRun": 150,  "exclusive": None},
    "chrome-reptilian-blue":      {"name": "Reptilian Blue Refractor",    "printRun": 150,  "exclusive": None},
    "chrome-blue-shimmer":        {"name": "Blue Shimmer",                "printRun": 150,  "exclusive": None},
    "chrome-blue-mojo":           {"name": "Blue Mojo",                   "printRun": 150,  "exclusive": "Mega"},
    "chrome-blue-xfractor":       {"name": "Blue X-Fractor",              "printRun": 150,  "exclusive": "Hobby"},
    "chrome-blue-geometric":      {"name": "Blue Geometric",              "printRun": 150,  "exclusive": "Breaker"},
    "chrome-aqua-mojo":           {"name": "Aqua Mojo",                   "printRun": 125,  "exclusive": "Mega"},
    "chrome-aqua-xfractor":       {"name": "Aqua X-Fractor",              "printRun": 125,  "exclusive": None},
    "chrome-floorboard":          {"name": "Floorboard Refractor",        "printRun": 125,  "exclusive": "Jumbo"},
    "chrome-aqua":                {"name": "Aqua Refractor",              "printRun": 125,  "exclusive": None},
    "chrome-mini-diamond-100":    {"name": "Mini-Diamond Refractor",      "printRun": 100,  "exclusive": "Hobby"},
    "chrome-steel-metal":         {"name": "Steel Metal Refractor",       "printRun": 100,  "exclusive": None},
    "chrome-green":               {"name": "Green Refractor",             "printRun": 99,   "exclusive": "Retail"},
    "chrome-green-mojo":          {"name": "Green Mojo",                  "printRun": 99,   "exclusive": "Mega"},
    "chrome-reptilian-green":     {"name": "Reptilian Green Refractor",   "printRun": 99,   "exclusive": "Retail"},
    "chrome-green-shimmer":       {"name": "Green Shimmer Refractor",     "printRun": 99,   "exclusive": "Retail"},
    "chrome-green-geometric":     {"name": "Green Geometric",             "printRun": 99,   "exclusive": "Breaker"},
    "chrome-yellow":               {"name": "Yellow Refractor",           "printRun": 75,   "exclusive": None},
    "chrome-yellow-xfractor":     {"name": "Yellow X-Fractor",            "printRun": 75,   "exclusive": "Hobby/Jumbo"},
    "chrome-yellow-wave":         {"name": "Yellow Wave Refractor",       "printRun": 75,   "exclusive": "Hobby/Jumbo"},
    "chrome-yellow-mojo":         {"name": "Yellow Mojo",                 "printRun": 75,   "exclusive": "Mega"},
    "chrome-gold":                {"name": "Gold Refractor",              "printRun": 50,   "exclusive": None},
    "chrome-gold-shimmer":        {"name": "Gold Shimmer Refractor",      "printRun": 50,   "exclusive": None},
    "chrome-reptilian-gold":      {"name": "Reptilian Gold Refractor",    "printRun": 50,   "exclusive": None},
    "chrome-gold-mojo":           {"name": "Gold Mojo",                   "printRun": 50,   "exclusive": "Mega"},
    "chrome-gold-geometric":      {"name": "Gold Geometric",              "printRun": 50,   "exclusive": "Breaker"},
    "chrome-orange":              {"name": "Orange Refractor",            "printRun": 25,   "exclusive": "Hobby"},
    "chrome-orange-shimmer":      {"name": "Orange Shimmer Refractor",    "printRun": 25,   "exclusive": "Hobby"},
    "chrome-reptilian-orange":    {"name": "Reptilian Orange Refractor",  "printRun": 25,   "exclusive": "Hobby"},
    "chrome-orange-mojo":         {"name": "Orange Mojo",                 "printRun": 25,   "exclusive": "Mega"},
    "chrome-orange-geometric":    {"name": "Orange Geometric",            "printRun": 25,   "exclusive": "Breaker"},
    "chrome-rose-gold":           {"name": "Rose Gold Refractor",         "printRun": 15,   "exclusive": None},
    "chrome-rose-gold-mini":      {"name": "Rose Gold Mini-Diamond Refractor", "printRun": 15, "exclusive": None},
    "chrome-rose-gold-xfractor":  {"name": "Rose Gold X-Fractor",         "printRun": 15,   "exclusive": None},
    "chrome-black":               {"name": "Black Refractor",             "printRun": 10,   "exclusive": None},
    "chrome-black-xfractor":      {"name": "Black X-Fractor",             "printRun": 10,   "exclusive": None},
    "chrome-black-geometric":     {"name": "Black Geometric",             "printRun": 10,   "exclusive": "Breaker"},
    "chrome-black-mojo":          {"name": "Black Mojo",                  "printRun": 10,   "exclusive": "Mega"},
    "chrome-red":                 {"name": "Red Refractor",               "printRun": 5,    "exclusive": None},
    "chrome-red-lava":            {"name": "Red Lava Refractor",          "printRun": 5,    "exclusive": None},
    "chrome-red-mojo":            {"name": "Red Mojo",                    "printRun": 5,    "exclusive": "Mega"},
    "chrome-red-xfractor":        {"name": "Red X-Fractor",               "printRun": 5,    "exclusive": "Jumbo"},
    "chrome-reptilian-red":       {"name": "Reptilian Red Refractor",     "printRun": 5,    "exclusive": None},
    "chrome-red-geometric":       {"name": "Red Geometric",               "printRun": 5,    "exclusive": "Breaker"},
    "chrome-firefractor":         {"name": "FireFractor",                 "printRun": 3,    "exclusive": "Value"},
    "chrome-superfractor":        {"name": "Superfractor",                "printRun": 1,    "exclusive": "Hobby"},
    "chrome-rose-gold-mojo":      {"name": "Rose Gold Mojo",              "printRun": 1,    "exclusive": "Mega"},

    # Crystallized parallels
    "crystal-gold":               {"name": "Gold Crystal Refractor",      "printRun": 50,   "exclusive": None},
    "crystal-orange":             {"name": "Orange Crystal Refractor",    "printRun": 25,   "exclusive": None},
    "crystal-red":                {"name": "Red Crystal Refractor",       "printRun": 5,    "exclusive": None},
}

# Common parallel groupings (referenced by subsets to avoid repetition)
NBA_BASE_PAPER_PARALLELS = [
    "paper-purple-pattern", "paper-pink", "paper-blue",
    "paper-green", "paper-green-pattern", "paper-yellow", "paper-gold",
    "paper-orange", "paper-black", "paper-black-pattern", "paper-red", "paper-platinum",
]

NBA_BASE_CHROME_PARALLELS = [
    "chrome-geometric", "chrome-mojo", "chrome-reptilian", "chrome-mini-diamond",
    "chrome-refractor", "chrome-lava", "chrome-fuchsia-mojo", "chrome-speckle",
    "chrome-burgundy-mojo", "chrome-purple", "chrome-purple-mojo", "chrome-fuchsia",
    "chrome-reptilian-fuchsia", "chrome-pink-mojo", "chrome-navy-mojo", "chrome-blue",
    "chrome-reptilian-blue", "chrome-blue-shimmer", "chrome-blue-mojo", "chrome-aqua-mojo",
    "chrome-floorboard", "chrome-steel-metal", "chrome-green", "chrome-green-mojo",
    "chrome-reptilian-green", "chrome-green-shimmer", "chrome-green-geometric",
    "chrome-yellow", "chrome-yellow-xfractor", "chrome-yellow-wave", "chrome-yellow-mojo",
    "chrome-gold", "chrome-gold-shimmer", "chrome-reptilian-gold", "chrome-gold-mojo",
    "chrome-gold-geometric", "chrome-orange", "chrome-orange-shimmer",
    "chrome-reptilian-orange", "chrome-orange-mojo", "chrome-orange-geometric",
    "chrome-rose-gold", "chrome-rose-gold-mini", "chrome-rose-gold-xfractor",
    "chrome-black", "chrome-black-xfractor", "chrome-black-geometric", "chrome-red",
    "chrome-red-lava", "chrome-red-mojo", "chrome-red-xfractor", "chrome-reptilian-red",
    "chrome-red-geometric", "chrome-firefractor", "chrome-superfractor", "chrome-rose-gold-mojo",
]

CHROME_PROSPECT_PARALLELS = [
    "chrome-geometric", "chrome-mojo", "chrome-reptilian", "chrome-mini-diamond",
    "chrome-refractor", "chrome-lava", "chrome-fuchsia-mojo", "chrome-speckle",
    "chrome-burgundy-mojo", "chrome-purple", "chrome-purple-mojo", "chrome-fuchsia",
    "chrome-pink-mojo", "chrome-navy-mojo", "chrome-reptilian-blue", "chrome-blue",
    "chrome-blue-mojo", "chrome-aqua-mojo", "chrome-aqua-xfractor", "chrome-floorboard",
    "chrome-steel-metal", "chrome-green", "chrome-green-mojo", "chrome-reptilian-green",
    "chrome-green-shimmer", "chrome-green-geometric", "chrome-yellow",
    "chrome-yellow-xfractor", "chrome-yellow-mojo", "chrome-gold", "chrome-reptilian-gold",
    "chrome-gold-geometric", "chrome-gold-mojo", "chrome-orange", "chrome-reptilian-orange",
    "chrome-orange-mojo", "chrome-orange-geometric", "chrome-rose-gold",
    "chrome-rose-gold-mini", "chrome-black", "chrome-black-xfractor",
    "chrome-black-geometric", "chrome-black-mojo", "chrome-red", "chrome-reptilian-red",
    "chrome-red-mojo", "chrome-red-geometric", "chrome-firefractor", "chrome-superfractor",
    "chrome-rose-gold-mojo",
]

CHROME_AUTO_PARALLELS = [
    "chrome-refractor", "chrome-speckle", "chrome-purple", "chrome-blue",
    "chrome-blue-xfractor", "chrome-mini-diamond-100", "chrome-green",
    "chrome-green-geometric", "chrome-green-shimmer", "chrome-reptilian-green",
    "chrome-yellow", "chrome-gold", "chrome-gold-geometric", "chrome-gold-shimmer",
    "chrome-reptilian-orange", "chrome-orange", "chrome-orange-geometric",
    "chrome-orange-shimmer", "chrome-black", "chrome-black-geometric",
    "chrome-black-xfractor", "chrome-red", "chrome-red-geometric", "chrome-red-lava",
    "chrome-firefractor", "chrome-superfractor",
]

CHROME_AUTO_PARALLELS_VET = CHROME_AUTO_PARALLELS + ["chrome-blue-geometric"]

INSERT_COMMON_PARALLELS = [
    "chrome-refractor", "chrome-geometric", "chrome-purple", "chrome-fuchsia",
    "chrome-mini-diamond", "chrome-aqua", "chrome-green", "chrome-gold",
    "chrome-gold-geometric", "chrome-orange", "chrome-orange-geometric",
    "chrome-black-geometric", "chrome-red", "chrome-red-geometric", "chrome-superfractor",
]

MEGA_INSERT_PARALLELS = [
    "chrome-blue-mojo", "chrome-green-mojo", "chrome-yellow-mojo", "chrome-gold-mojo",
    "chrome-orange-mojo", "chrome-black-mojo", "chrome-red-mojo", "chrome-rose-gold-mojo",
]

GLASS_PARALLELS = ["chrome-gold", "chrome-orange", "chrome-red", "chrome-superfractor"]

PROMO_AUTO_PARALLELS = [
    "chrome-gold", "chrome-orange", "chrome-black", "chrome-red", "chrome-superfractor",
]

PAPER_AUTO_PARALLELS = [
    "paper-blue", "paper-green", "paper-gold", "paper-orange", "paper-red", "paper-platinum",
]

# ---------------------------------------------------------------------------
# Card lists per subset
# ---------------------------------------------------------------------------

# Base 200 — players + teams + RC flag
BASE_200 = [
    # 1-55: Rookies (#37 Buddy Hield is NOT a rookie, see is_rc list)
    (1,  "Cooper Flagg",            "Dallas Mavericks"),
    (2,  "Dylan Harper",            "San Antonio Spurs"),
    (3,  "VJ Edgecombe",            "Philadelphia 76ers"),
    (4,  "Kon Knueppel",            "Charlotte Hornets"),
    (5,  "Ace Bailey",              "Utah Jazz"),
    (6,  "Tre Johnson III",         "Washington Wizards"),
    (7,  "Jeremiah Fears",          "New Orleans Pelicans"),
    (8,  "Egor Dëmin",              "Brooklyn Nets"),
    (9,  "Collin Murray-Boyles",    "Toronto Raptors"),
    (10, "Khaman Maluach",          "Phoenix Suns"),
    (11, "Cedric Coward",           "Memphis Grizzlies"),
    (12, "Noa Essengue",            "Chicago Bulls"),
    (13, "Derik Queen",             "New Orleans Pelicans"),
    (14, "Carter Bryant",           "San Antonio Spurs"),
    (15, "Thomas Sorber",           "Oklahoma City Thunder"),
    (16, "Yang Hansen",             "Portland Trail Blazers"),
    (17, "Joan Beringer",           "Minnesota Timberwolves"),
    (18, "Walter Clayton Jr.",      "Utah Jazz"),
    (19, "Nolan Traore",            "Brooklyn Nets"),
    (20, "Kasparas Jakučionis",     "Miami Heat"),
    (21, "Will Riley",              "Washington Wizards"),
    (22, "Drake Powell",            "Brooklyn Nets"),
    (23, "Asa Newell",              "Atlanta Hawks"),
    (24, "Nique Clifford",          "Sacramento Kings"),
    (25, "Jase Richardson",         "Orlando Magic"),
    (26, "Ben Saraf",               "Brooklyn Nets"),
    (27, "Danny Wolf",              "Brooklyn Nets"),
    (28, "Hugo González",           "Boston Celtics"),
    (29, "Liam McNeeley",           "Charlotte Hornets"),
    (30, "Yanic Konan-Niederhäuser","Los Angeles Clippers"),
    (31, "Rasheer Fleming",         "Phoenix Suns"),
    (32, "Noah Penda",              "Orlando Magic"),
    (33, "Sion James",              "Charlotte Hornets"),
    (34, "Ryan Kalkbrenner",        "Charlotte Hornets"),
    (35, "Johni Broome",            "Philadelphia 76ers"),
    (36, "Adou Thiero",             "Los Angeles Lakers"),
    (37, "Buddy Hield",             "Golden State Warriors"),  # NOT RC
    (38, "Chaz Lanier",             "Detroit Pistons"),
    (39, "Kam Jones",               "Indiana Pacers"),
    (40, "Alijah Martin",           "Toronto Raptors"),
    (41, "Micah Peavy",             "New Orleans Pelicans"),
    (42, "Koby Brea",               "Phoenix Suns"),
    (43, "Maxime Raynaud",          "Sacramento Kings"),
    (44, "Jamir Watkins",           "Washington Wizards"),
    (45, "Brooks Barnhizer",        "Oklahoma City Thunder"),
    (46, "Javon Small",             "Memphis Grizzlies"),
    (47, "Kobe Sanders",            "Los Angeles Clippers"),
    (48, "Alex Toohey",             "Golden State Warriors"),
    (49, "John Tonje",              "Utah Jazz"),
    (50, "Taelon Peter",            "Indiana Pacers"),
    (51, "Lachlan Olbrich",         "Chicago Bulls"),
    (52, "Will Richard",            "Golden State Warriors"),
    (53, "Max Shulga",              "Boston Celtics"),
    (54, "Jahmai Mashack",          "Memphis Grizzlies"),
    (55, "Tyrese Proctor",          "Cleveland Cavaliers"),
    # 56-200 Veterans
    (56,  "Jayson Tatum",           "Boston Celtics"),
    (57,  "Jaylen Brown",           "Boston Celtics"),
    (58,  "Derrick White",          "Boston Celtics"),
    (59,  "Cam Thomas",             "Brooklyn Nets"),
    (60,  "Jalen Wilson",           "Brooklyn Nets"),
    (61,  "Cameron Johnson",        "Brooklyn Nets"),
    (62,  "Jalen Brunson",          "New York Knicks"),
    (63,  "OG Anunoby",             "New York Knicks"),
    (64,  "Karl-Anthony Towns",     "New York Knicks"),
    (65,  "Jared McCain",           "Philadelphia 76ers"),
    (66,  "Tyrese Maxey",           "Philadelphia 76ers"),
    (67,  "Joel Embiid",            "Philadelphia 76ers"),
    (68,  "Scottie Barnes",         "Toronto Raptors"),
    (69,  "Immanuel Quickley",      "Toronto Raptors"),
    (70,  "Gradey Dick",            "Toronto Raptors"),
    (71,  "Coby White",             "Chicago Bulls"),
    (72,  "Josh Giddey",            "Chicago Bulls"),
    (73,  "Matas Buzelis",          "Chicago Bulls"),
    (74,  "Cade Cunningham",        "Detroit Pistons"),
    (75,  "Jalen Duren",            "Detroit Pistons"),
    (76,  "Ausar Thompson",         "Detroit Pistons"),
    (77,  "Tyrese Haliburton",      "Indiana Pacers"),
    (78,  "Bennedict Mathurin",     "Indiana Pacers"),
    (79,  "Pascal Siakam",          "Indiana Pacers"),
    (80,  "Giannis Antetokounmpo",  "Milwaukee Bucks"),
    (81,  "Damian Lillard",         "Milwaukee Bucks"),
    (82,  "Kyle Kuzma",             "Milwaukee Bucks"),
    (83,  "Trae Young",             "Atlanta Hawks"),
    (84,  "Zaccharie Risacher",     "Atlanta Hawks"),
    (85,  "Jalen Johnson",          "Atlanta Hawks"),
    (86,  "LaMelo Ball",            "Charlotte Hornets"),
    (87,  "Brandon Miller",         "Charlotte Hornets"),
    (88,  "Tyler Herro",            "Miami Heat"),
    (89,  "Bam Adebayo",            "Miami Heat"),
    (90,  "Kel'el Ware",            "Miami Heat"),
    (91,  "Donovan Mitchell",       "Cleveland Cavaliers"),
    (92,  "Darius Garland",         "Cleveland Cavaliers"),
    (93,  "Evan Mobley",            "Cleveland Cavaliers"),
    (94,  "Paolo Banchero",         "Orlando Magic"),
    (95,  "Franz Wagner",           "Orlando Magic"),
    (96,  "Anthony Black",          "Orlando Magic"),
    (97,  "Jordan Poole",           "Washington Wizards"),
    (98,  "Bilal Coulibaly",        "Washington Wizards"),
    (99,  "Alex Sarr",              "Washington Wizards"),
    (100, "Nikola Jokić",           "Denver Nuggets"),
    (101, "Jamal Murray",           "Denver Nuggets"),
    (102, "Russell Westbrook",      "Denver Nuggets"),
    (103, "Anthony Edwards",        "Minnesota Timberwolves"),
    (104, "Naz Reid",               "Minnesota Timberwolves"),
    (105, "Terrence Shannon Jr.",   "Minnesota Timberwolves"),
    (106, "Shai Gilgeous-Alexander","Oklahoma City Thunder"),
    (107, "Jalen Williams",         "Oklahoma City Thunder"),
    (108, "Chet Holmgren",          "Oklahoma City Thunder"),
    (109, "Scoot Henderson",        "Portland Trail Blazers"),
    (110, "Shaedon Sharpe",         "Portland Trail Blazers"),
    (111, "Toumani Camara",         "Portland Trail Blazers"),
    (112, "Lauri Markkanen",        "Utah Jazz"),
    (113, "Kyle Filipowski",        "Utah Jazz"),
    (114, "Isaiah Collier",         "Utah Jazz"),
    (115, "Stephen Curry",          "Golden State Warriors"),
    (116, "Jimmy Butler III",       "Golden State Warriors"),
    (117, "Draymond Green",         "Golden State Warriors"),
    (118, "Kawhi Leonard",          "Los Angeles Clippers"),
    (119, "James Harden",           "Los Angeles Clippers"),
    (120, "Ivica Zubac",            "Los Angeles Clippers"),
    (121, "LeBron James",           "Los Angeles Lakers"),
    (122, "Bronny James Jr.",       "Los Angeles Lakers"),
    (123, "Luka Dončić",            "Los Angeles Lakers"),
    (124, "Devin Booker",           "Phoenix Suns"),
    (125, "Kevin Durant",           "Houston Rockets"),
    (126, "Bradley Beal",           "Phoenix Suns"),
    (127, "DeMar DeRozan",          "Sacramento Kings"),
    (128, "Zach LaVine",            "Sacramento Kings"),
    (129, "Domantas Sabonis",       "Sacramento Kings"),
    (130, "Kyrie Irving",           "Dallas Mavericks"),
    (131, "Anthony Davis",          "Dallas Mavericks"),
    (132, "Klay Thompson",          "Dallas Mavericks"),
    (133, "Alperen Sengun",         "Houston Rockets"),
    (134, "Amen Thompson",          "Houston Rockets"),
    (135, "Reed Sheppard",          "Houston Rockets"),
    (136, "Ja Morant",              "Memphis Grizzlies"),
    (137, "Jaren Jackson Jr.",      "Memphis Grizzlies"),
    (138, "Desmond Bane",           "Memphis Grizzlies"),
    (139, "Zach Edey",              "Memphis Grizzlies"),
    (140, "Herbert Jones",          "New Orleans Pelicans"),
    (141, "Trey Murphy III",        "New Orleans Pelicans"),
    (142, "Dejounte Murray",        "New Orleans Pelicans"),
    (143, "Victor Wembanyama",      "San Antonio Spurs"),
    (144, "De'Aaron Fox",           "San Antonio Spurs"),
    (145, "Stephon Castle",         "San Antonio Spurs"),
    (146, "Chris Paul",             "San Antonio Spurs"),
    (147, "Jeremy Sochan",          "San Antonio Spurs"),
    (148, "Kristaps Porzingis",     "Boston Celtics"),
    (149, "Payton Pritchard",       "Boston Celtics"),
    (150, "Nic Claxton",            "Brooklyn Nets"),
    (151, "Noah Clowney",           "Brooklyn Nets"),
    (152, "Mikal Bridges",          "New York Knicks"),
    (153, "Josh Hart",              "New York Knicks"),
    (154, "Paul George",            "Philadelphia 76ers"),
    (155, "Guerschon Yabusele",     "Philadelphia 76ers"),
    (156, "RJ Barrett",             "Toronto Raptors"),
    (157, "Nikola Vučević",         "Chicago Bulls"),
    (158, "Patrick Williams",       "Chicago Bulls"),
    (159, "Jaden Ivey",             "Detroit Pistons"),
    (160, "Ron Holland II",         "Detroit Pistons"),
    (161, "Myles Turner",           "Indiana Pacers"),
    (162, "Obi Toppin",             "Indiana Pacers"),
    (163, "Andrew Nembhard",        "Indiana Pacers"),
    (164, "AJ Green",               "Milwaukee Bucks"),
    (165, "Gary Trent Jr.",         "Milwaukee Bucks"),
    (166, "Dyson Daniels",          "Atlanta Hawks"),
    (167, "Onyeka Okongwu",         "Atlanta Hawks"),
    (168, "Mark Williams",          "Charlotte Hornets"),
    (169, "Tidjane Salaün",         "Charlotte Hornets"),
    (170, "Andrew Wiggins",         "Miami Heat"),
    (171, "Jaime Jaquez Jr.",       "Miami Heat"),
    (172, "Jarrett Allen",          "Cleveland Cavaliers"),
    (173, "Jaylon Tyson",           "Cleveland Cavaliers"),
    (174, "Jalen Suggs",            "Orlando Magic"),
    (175, "Tristan da Silva",       "Orlando Magic"),
    (176, "Bub Carrington",         "Washington Wizards"),
    (177, "Kyshawn George",         "Washington Wizards"),
    (178, "AJ Johnson",             "Washington Wizards"),
    (179, "Michael Porter Jr.",     "Denver Nuggets"),
    (180, "Peyton Watson",          "Denver Nuggets"),
    (181, "Christian Braun",        "Denver Nuggets"),
    (182, "Rob Dillingham",         "Minnesota Timberwolves"),
    (183, "Julius Randle",          "Minnesota Timberwolves"),
    (184, "Luguentz Dort",          "Oklahoma City Thunder"),
    (185, "Cason Wallace",          "Oklahoma City Thunder"),
    (186, "Aaron Wiggins",          "Oklahoma City Thunder"),
    (187, "Deni Avdija",            "Portland Trail Blazers"),
    (188, "Donovan Clingan",        "Portland Trail Blazers"),
    (189, "Keyonte George",         "Utah Jazz"),
    (190, "Jordan Clarkson",        "Utah Jazz"),
    (191, "Jonathan Kuminga",       "Golden State Warriors"),
    (192, "Norman Powell",          "Los Angeles Clippers"),
    (193, "Austin Reaves",          "Los Angeles Lakers"),
    (194, "Dalton Knecht",          "Los Angeles Lakers"),
    (195, "Ryan Dunn",              "Phoenix Suns"),
    (196, "Oso Ighodaro",           "Phoenix Suns"),
    (197, "Devin Carter",           "Sacramento Kings"),
    (198, "Dereck Lively II",       "Dallas Mavericks"),
    (199, "Jalen Green",            "Houston Rockets"),
    (200, "Santi Aldama",           "Memphis Grizzlies"),
]

# RC tag — cards 1-55 except #37 (Buddy Hield)
def is_rc_base(num: int) -> bool:
    return 1 <= num <= 55 and num != 37

# Prospects 100 (NCAA)
PROSPECTS_100 = [
    (1,  "AJ Dybantsa",         "BYU"),
    (2,  "Darryn Peterson",     "Kansas"),
    (3,  "Koa Peat",            "Arizona"),
    (4,  "Kiyan Anthony",       "Syracuse"),
    (5,  "Nate Ament",          "Tennessee"),
    (6,  "Jasper Johnson",      "Kentucky"),
    (7,  "Isiah Harwell",       "Houston"),
    (8,  "Bryson Tiller",       "Kansas"),
    (9,  "Obi Agbim",           "Baylor"),
    (10, "Shelton Henderson",   "Miami"),
    (11, "Tounde Yessoufou",    "Baylor"),
    (12, "Mikel Brown Jr.",     "Louisville"),
    (13, "Sienna Betts",        "UCLA"),
    (14, "Acaden Lewis",        "Villanova"),
    (15, "Madison Booker",      "Texas"),
    (16, "Jason Edwards",       "Providence"),
    (17, "Josh Dix",            "Creighton"),
    (18, "Niko Bundalo",        "Ole Miss"),
    (19, "Shon Abaev",          "Cincinnati"),
    (20, "Silas Demary Jr.",    "UConn"),
    (21, "Trey Kaufman-Renn",   "Purdue"),
    (22, "Zuby Ejiofor",        "St. John's"),
    (23, "Jaland Lowe",         "Kentucky"),
    (24, "Joe Grahovac",        "St. Bonaventure"),
    (25, "Kiyomi McMiller",     "Penn State"),
    (26, "Michael Rataj",       "Baylor"),
    (27, "Reed Bailey",         "Indiana"),
    (28, "Xaivian Lee",         "Florida"),
    (29, "Braeden Shrewsberry", "Notre Dame"),
    (30, "Cotie McMahon",       "Ole Miss"),
    (31, "Serah Williams",      "UConn"),
    (32, "Owen Freeman",        "Creighton"),
    (33, "Aaliyah Crump",       "Texas"),
    (34, "Agot Makeer",         "South Carolina"),
    (35, "Coen Carr",           "Michigan State"),
    (36, "Darrion Williams",    "NC State"),
    (37, "Derek Dixon",         "UNC"),
    (38, "Hailee Swain",        "Stanford"),
    (39, "Kaylene Smikle",      "Maryland"),
    (40, "Milos Uzan",          "Houston"),
    (41, "Sadiq White",         "Syracuse"),
    (42, "Tarris Reed Jr.",     "UConn"),
    (43, "Wesley Yates III",    "Washington"),
    (44, "Lara Somfai",         "Stanford"),
    (45, "Christian Anderson",  "Texas Tech"),
    (46, "Davion Hannah",       "Alabama"),
    (47, "Davis Fogle",         "Gonzaga"),
    (48, "Grace Knox",          "LSU"),
    (49, "Isaiah Denis",        "UNC"),
    (50, "Addison Deal",        "Iowa"),
    (51, "Brayden Burries",     "Arizona"),
    (52, "Bryce Lindsay",       "Villanova"),
    (53, "Cam Ward",            "Michigan State"),
    (54, "Chase Ross",          "Marquette"),
    (55, "Deniya Prawl",        "Tennessee"),
    (56, "Devin McGlockton",    "Vanderbilt"),
    (57, "Donald Hand Jr.",     "Boston College"),
    (58, "Ja'Kobi Gillespie",   "Tennessee"),
    (59, "Jamier Jones",        "Providence"),
    (60, "Keyshawn Hall",       "Auburn"),
    (61, "Leah Macy",           "Notre Dame"),
    (62, "Nick Martinelli",     "Northwestern"),
    (63, "Nyla Brooks",         "UNC"),
    (64, "Pharrel Payne",       "Maryland"),
    (65, "Raegan Beers",        "Oklahoma"),
    (66, "Richie Saunders",     "BYU"),
    (67, "Winters Grady",       "Michigan"),
    (68, "Yarden Garzon",       "Maryland"),
    (69, "Darianna Alexander",  "Cincinnati"),
    (70, "Jeremiah Wilkinson",  "Georgia"),
    (71, "Kara Dunn",           "USC"),
    (72, "Boopie Miller",       "SMU"),
    (73, "ZaKiyah Johnson",     "LSU"),
    (74, "Jaida Civil",         "Tennessee"),
    (75, "Alexandra Eschmeyer", "Stanford"),
    (76, "Aliyahna Morris",     "California"),
    (77, "CJ Ingram",           "Florida"),
    (78, "John Blackwell",      "Wisconsin"),
    (79, "Tobe Awaka",          "Arizona"),
    (80, "Sarah Strong",        "UConn"),
    (81, "Tre Holloman",        "NC State"),
    (82, "Kaelyn Carroll",      "Kentucky"),
    (83, "Caleb Wilson",        "UNC"),
    (84, "Ayla McDowell",       "South Carolina"),
    (85, "Emilee Skinner",      "Duke"),
    (86, "Ta'Niya Latson",      "South Carolina"),
    (87, "Oziyah Sellers",      "St. John's"),
    (88, "Nate Bittle",         "Oregon"),
    (89, "Kelis Fisher",        "UConn"),
    (90, "Bennett Stirtz",      "Iowa"),
    (91, "Ace Flagg",           "Maine"),
    (92, "Nate Calmese",        "Wake Forest"),
    (93, "JT Toppin",           "Texas Tech"),
    (94, "Braden Smith",        "Purdue"),
    (95, "Kohl Rosario",        "Kansas"),
    (96, "Juju Watkins",        "USC"),
    (97, "Brandon Garrison",    "Kentucky"),
    (98, "Otega Oweh",          "Kentucky"),
    (99, "Sebastian Wilkins",   "Duke"),
    (100,"Caleb Foster",        "Duke"),
]

# Etched In Glass — Base (10 cards) — first 7 RCs + 3 marquee vets
ETCHED_GLASS_BASE = [
    ("NBE-1",  "Cooper Flagg",            "Dallas Mavericks"),
    ("NBE-2",  "Dylan Harper",            "San Antonio Spurs"),
    ("NBE-3",  "VJ Edgecombe",            "Philadelphia 76ers"),
    ("NBE-4",  "Kon Knueppel",            "Charlotte Hornets"),
    ("NBE-5",  "Ace Bailey",              "Utah Jazz"),
    ("NBE-6",  "Tre Johnson III",         "Washington Wizards"),
    ("NBE-7",  "Jeremiah Fears",          "New Orleans Pelicans"),
    ("NBE-8",  "Stephen Curry",           "Golden State Warriors"),
    ("NBE-9",  "Shai Gilgeous-Alexander", "Oklahoma City Thunder"),
    ("NBE-10", "Luka Dončić",             "Los Angeles Lakers"),
]

# Etched In Glass — Chrome Prospects (5 cards)
ETCHED_GLASS_PROSPECTS = [
    ("CPE-1", "AJ Dybantsa",      "BYU"),
    ("CPE-2", "Darryn Peterson",  "Kansas"),
    ("CPE-3", "Madison Booker",   "Texas"),
    ("CPE-4", "Juju Watkins",     "USC"),
    ("CPE-5", "Koa Peat",         "Arizona"),
]

# Retrofractor variations (2 base + 1 auto)
RETROFRACTOR_BASE = [
    ("RV-BR", "Bill Russell",       "San Francisco"),
    ("RV-SA", "Shaquille O'Neal",   "LSU"),
]
RETROFRACTOR_AUTO = [
    ("RAV-SO", "Shaquille O'Neal", "LSU"),
]

# Red Rookie Variations — first 50 of the rookie checklist (BRR-1 through BRR-50)
# Note: BRR-37 is Will Richard (Golden State) per article — not Buddy Hield
RED_ROOKIES = []
for i in range(1, 51):
    if i == 37:
        RED_ROOKIES.append((f"BRR-{i}", "Will Richard", "Golden State Warriors"))
    else:
        # Map to base 1-50 (skipping RC offset for #37)
        base_num = i  # cards 1-50 use the same player as base, except 37
        # BRR-37 is Will Richard, not Buddy Hield. Adjust accordingly:
        player, team = next((p, t) for n, p, t in BASE_200 if n == base_num)
        RED_ROOKIES.append((f"BRR-{i}", player, team))
# Override #37 explicitly
RED_ROOKIES[36] = ("BRR-37", "Will Richard", "Golden State Warriors")

# Chrome Prospect Autographs (101 cards) — mostly subset of prospects + Boozers added late
CHROME_PROSPECT_AUTOS = [
    ("CPA-AC",  "Aaliyah Crump",       "Texas"),
    ("CPA-AD",  "AJ Dybantsa",         "BYU"),
    ("CPA-AE",  "Addison Deal",        "Iowa"),
    ("CPA-AF",  "Ace Flagg",           "Maine"),
    ("CPA-AL",  "Acaden Lewis",        "Villanova"),
    ("CPA-AM",  "Agot Makeer",         "South Carolina"),
    ("CPA-AO",  "Aliyahna Morris",     "California"),
    ("CPA-AS",  "Alexandra Eschmeyer", "Stanford"),
    ("CPA-AW",  "Ayla McDowell",       "South Carolina"),
    ("CPA-BB",  "Brayden Burries",     "Arizona"),
    ("CPA-BG",  "Brandon Garrison",    "Kentucky"),
    ("CPA-BI",  "Bennett Stirtz",      "Iowa"),
    ("CPA-BL",  "Bryce Lindsay",       "Villanova"),
    ("CPA-BM",  "Braden Smith",        "Purdue"),
    ("CPA-BR",  "Boopie Miller",       "SMU"),
    ("CPA-BS",  "Braeden Shrewsberry", "Notre Dame"),
    ("CPA-BT",  "Bryson Tiller",       "Kansas"),
    ("CPA-CA",  "Christian Anderson",  "Texas Tech"),
    ("CPA-CC",  "Coen Carr",           "Michigan State"),
    ("CPA-CF",  "Caleb Foster",        "Duke"),
    ("CPA-CI",  "CJ Ingram",           "Florida"),
    ("CPA-CL",  "Caleb Wilson",        "UNC"),
    ("CPA-CM",  "Cotie McMahon",       "Ole Miss"),
    ("CPA-CR",  "Chase Ross",          "Marquette"),
    ("CPA-CW",  "Cam Ward",            "Michigan State"),
    ("CPA-DD",  "Derek Dixon",         "UNC"),
    ("CPA-DF",  "Davis Fogle",         "Gonzaga"),
    ("CPA-DH",  "Davion Hannah",       "Alabama"),
    ("CPA-DL",  "Darianna Alexander",  "Cincinnati"),
    ("CPA-DM",  "Devin McGlockton",    "Vanderbilt"),
    ("CPA-DN",  "Donald Hand Jr.",     "Boston College"),
    ("CPA-DP",  "Darryn Peterson",     "Kansas"),
    ("CPA-DR",  "Deniya Prawl",        "Tennessee"),
    ("CPA-DW",  "Darrion Williams",    "NC State"),
    ("CPA-ES",  "Emilee Skinner",      "Duke"),
    ("CPA-GK",  "Grace Knox",          "LSU"),
    ("CPA-HS",  "Hailee Swain",        "Stanford"),
    ("CPA-ID",  "Isaiah Denis",        "UNC"),
    ("CPA-IH",  "Isiah Harwell",       "Houston"),
    ("CPA-JA",  "Juju Watkins",        "USC"),
    ("CPA-JB",  "John Blackwell",      "Wisconsin"),
    ("CPA-JC",  "Jaida Civil",         "Tennessee"),
    ("CPA-JD",  "Josh Dix",            "Creighton"),
    ("CPA-JE",  "Jason Edwards",       "Providence"),
    ("CPA-JG",  "Joe Grahovac",        "St. Bonaventure"),
    ("CPA-JI",  "Ja'Kobi Gillespie",   "Tennessee"),
    ("CPA-JJ",  "Jasper Johnson",      "Kentucky"),
    ("CPA-JL",  "Jaland Lowe",         "Kentucky"),
    ("CPA-JO",  "Jamier Jones",        "Providence"),
    ("CPA-JT",  "JT Toppin",           "Texas Tech"),
    ("CPA-JW",  "Jeremiah Wilkinson",  "Georgia"),
    ("CPA-KA",  "Kiyan Anthony",       "Syracuse"),
    ("CPA-KC",  "Kaelyn Carroll",      "Kentucky"),
    ("CPA-KD",  "Kara Dunn",           "USC"),
    ("CPA-KF",  "Kelis Fisher",        "UConn"),
    ("CPA-KH",  "Keyshawn Hall",       "Auburn"),
    ("CPA-KM",  "Kiyomi McMiller",     "Penn State"),
    ("CPA-KP",  "Koa Peat",            "Arizona"),
    ("CPA-KR",  "Kohl Rosario",        "Kansas"),
    ("CPA-KS",  "Kaylene Smikle",      "Maryland"),
    ("CPA-LM",  "Leah Macy",           "Notre Dame"),
    ("CPA-LS",  "Lara Somfai",         "Stanford"),
    ("CPA-MB",  "Madison Booker",      "Texas"),
    ("CPA-MBJ", "Mikel Brown Jr.",     "Louisville"),
    ("CPA-MR",  "Michael Rataj",       "Baylor"),
    ("CPA-MU",  "Milos Uzan",          "Houston"),
    ("CPA-NA",  "Nate Ament",          "Tennessee"),
    ("CPA-NB",  "Niko Bundalo",        "Ole Miss"),
    ("CPA-NC",  "Nate Calmese",        "Wake Forest"),
    ("CPA-NI",  "Nate Bittle",         "Oregon"),
    ("CPA-NM",  "Nick Martinelli",     "Northwestern"),
    ("CPA-NR",  "Nyla Brooks",         "UNC"),
    ("CPA-OA",  "Obi Agbim",           "Baylor"),
    ("CPA-OF",  "Owen Freeman",        "Creighton"),
    ("CPA-OO",  "Otega Oweh",          "Kentucky"),
    ("CPA-OS",  "Oziyah Sellers",      "St. John's"),
    ("CPA-PP",  "Pharrel Payne",       "Maryland"),
    ("CPA-RB",  "Reed Bailey",         "Indiana"),
    ("CPA-RE",  "Raegan Beers",        "Oklahoma"),
    ("CPA-RS",  "Richie Saunders",     "BYU"),
    ("CPA-SA",  "Shon Abaev",          "Cincinnati"),
    ("CPA-SB",  "Sienna Betts",        "UCLA"),
    ("CPA-SD",  "Silas Demary Jr.",    "UConn"),
    ("CPA-SH",  "Shelton Henderson",   "Miami"),
    ("CPA-SI",  "Sebastian Wilkins",   "Duke"),
    ("CPA-SS",  "Sarah Strong",        "UConn"),
    ("CPA-SW",  "Serah Williams",      "UConn"),
    ("CPA-SWH", "Sadiq White",         "Syracuse"),
    ("CPA-TA",  "Tobe Awaka",          "Arizona"),
    ("CPA-TK",  "Trey Kaufman-Renn",   "Purdue"),
    ("CPA-TL",  "Ta'Niya Latson",      "South Carolina"),
    ("CPA-TR",  "Tarris Reed Jr.",     "UConn"),
    ("CPA-TY",  "Tounde Yessoufou",    "Baylor"),
    ("CPA-WG",  "Winters Grady",       "Michigan"),
    ("CPA-WY",  "Wesley Yates III",    "Washington"),
    ("CPA-XL",  "Xaivian Lee",         "Florida"),
    ("CPA-YG",  "Yarden Garzon",       "Maryland"),
    ("CPA-ZE",  "Zuby Ejiofor",        "St. John's"),
    ("CPA-ZJ",  "ZaKiyah Johnson",     "LSU"),
    ("CPA-CB",  "Cayden Boozer",       "Duke"),
    ("CPA-CO",  "Cameron Boozer",      "Duke"),
]

# Chrome Autographs (98 cards)
CHROME_AUTOS_NBA = [
    ("BCA-AA",  "Aaron Nesmith",            "Indiana Pacers"),
    ("BCA-AB",  "Ace Bailey",               "Utah Jazz"),
    ("BCA-AE",  "Anthony Edwards",          "Minnesota Timberwolves"),
    ("BCA-AL",  "Ajay Mitchell",            "Oklahoma City Thunder"),
    ("BCA-AM",  "Alijah Martin",            "Toronto Raptors"),
    ("BCA-AN",  "Asa Newell",               "Atlanta Hawks"),
    ("BCA-AO",  "Alex Toohey",              "Golden State Warriors"),
    ("BCA-AR",  "Anthony Black",            "Orlando Magic"),
    ("BCA-AS",  "Alex Sarr",                "Washington Wizards"),
    ("BCA-AT",  "Adou Thiero",              "Los Angeles Lakers"),
    ("BCA-BA",  "Ben Saraf",                "Brooklyn Nets"),
    ("BCA-BB",  "Brooks Barnhizer",         "Oklahoma City Thunder"),
    ("BCA-BM",  "Brandon Miller",           "Charlotte Hornets"),
    ("BCA-BR",  "Bronny James Jr.",         "Los Angeles Lakers"),
    ("BCA-CC",  "Cedric Coward",            "Memphis Grizzlies"),
    ("BCA-CF",  "Cooper Flagg",             "Dallas Mavericks"),
    ("BCA-CL",  "Chaz Lanier",              "Detroit Pistons"),
    ("BCA-CMB", "Collin Murray-Boyles",     "Toronto Raptors"),
    ("BCA-CW",  "Cam Whitmore",             "Houston Rockets"),
    ("BCA-DA",  "Deandre Ayton",            "Portland Trail Blazers"),
    ("BCA-DC",  "Devin Carter",             "Sacramento Kings"),
    ("BCA-DFS", "Dorian Finney-Smith",      "Los Angeles Lakers"),
    ("BCA-DH",  "Dylan Harper",             "San Antonio Spurs"),
    ("BCA-DI",  "Derrick White",            "Boston Celtics"),
    ("BCA-DJ",  "Dillon Jones",             "Oklahoma City Thunder"),
    ("BCA-DP",  "Drake Powell",             "Brooklyn Nets"),
    ("BCA-DQ",  "Derik Queen",              "New Orleans Pelicans"),
    ("BCA-DV",  "Devin Vassell",            "San Antonio Spurs"),
    ("BCA-DW",  "Danny Wolf",               "Brooklyn Nets"),
    ("BCA-ED",  "Egor Dëmin",               "Brooklyn Nets"),
    ("BCA-EF",  "Enrique Freeman",          "Indiana Pacers"),
    ("BCA-FW",  "Franz Wagner",             "Orlando Magic"),
    ("BCA-GA",  "Giannis Antetokounmpo",    "Milwaukee Bucks"),
    ("BCA-GD",  "Gradey Dick",              "Toronto Raptors"),
    ("BCA-IC",  "Isaiah Collier",           "Utah Jazz"),
    ("BCA-IZ",  "Ivica Zubac",              "Los Angeles Clippers"),
    ("BCA-JA",  "Jordan Hawkins",           "New Orleans Pelicans"),
    ("BCA-JB",  "Joan Beringer",            "Minnesota Timberwolves"),
    ("BCA-JC",  "Jordan Clarkson",          "Utah Jazz"),
    ("BCA-JE",  "John Tonje",               "Utah Jazz"),
    ("BCA-JI",  "Jaylin Williams",          "Oklahoma City Thunder"),
    ("BCA-JK",  "Jarace Walker",            "Indiana Pacers"),
    ("BCA-JL",  "Jalen Williams",           "Oklahoma City Thunder"),
    ("BCA-JM",  "Jahmai Mashack",           "Memphis Grizzlies"),
    ("BCA-JN",  "Jaylon Tyson",             "Cleveland Cavaliers"),
    ("BCA-JO",  "Johni Broome",             "Philadelphia 76ers"),
    ("BCA-JR",  "Jase Richardson",          "Orlando Magic"),
    ("BCA-JS",  "Javon Small",              "Memphis Grizzlies"),
    ("BCA-JT",  "Jayson Tatum",             "Boston Celtics"),
    ("BCA-JU",  "Jalen Brunson",            "New York Knicks"),
    ("BCA-JW",  "Jamir Watkins",            "Washington Wizards"),
    ("BCA-JY",  "Jamal Murray",             "Denver Nuggets"),
    ("BCA-KB",  "Koby Brea",                "Phoenix Suns"),
    ("BCA-KD",  "Kevin Durant",             "Houston Rockets"),
    ("BCA-KF",  "Kyle Filipowski",          "Utah Jazz"),
    ("BCA-KJ",  "Kasparas Jakučionis",      "Miami Heat"),
    ("BCA-KK",  "Kon Knueppel",             "Charlotte Hornets"),
    ("BCA-KM",  "Khaman Maluach",           "Phoenix Suns"),
    ("BCA-KO",  "Kam Jones",                "Indiana Pacers"),
    ("BCA-KS",  "Kobe Sanders",             "Los Angeles Clippers"),
    ("BCA-KW",  "Kel'el Ware",              "Miami Heat"),
    ("BCA-LBJ", "LeBron James",             "Los Angeles Lakers"),
    ("BCA-LM",  "Liam McNeeley",            "Charlotte Hornets"),
    ("BCA-LO",  "Lachlan Olbrich",          "Chicago Bulls"),
    ("BCA-MP",  "Micah Peavy",              "New Orleans Pelicans"),
    ("BCA-MR",  "Maxime Raynaud",           "Sacramento Kings"),
    ("BCA-MS",  "Max Shulga",               "Boston Celtics"),
    ("BCA-MT",  "Myles Turner",             "Indiana Pacers"),
    ("BCA-NC",  "Nique Clifford",           "Sacramento Kings"),
    ("BCA-NE",  "Noa Essengue",             "Chicago Bulls"),
    ("BCA-NJ",  "Nikola Jokić",             "Denver Nuggets"),
    ("BCA-NO",  "Nikola Topić",             "Oklahoma City Thunder"),
    ("BCA-NP",  "Noah Penda",               "Orlando Magic"),
    ("BCA-NT",  "Nolan Traore",             "Brooklyn Nets"),
    ("BCA-PB",  "Paolo Banchero",           "Orlando Magic"),
    ("BCA-QP",  "Quinten Post",             "Golden State Warriors"),
    ("BCA-RD",  "Rob Dillingham",           "Minnesota Timberwolves"),
    ("BCA-RF",  "Rasheer Fleming",          "Phoenix Suns"),
    ("BCA-RH",  "Ron Holland II",           "Detroit Pistons"),
    ("BCA-RK",  "Ryan Kalkbrenner",         "Charlotte Hornets"),
    ("BCA-RU",  "Ryan Dunn",                "Phoenix Suns"),
    ("BCA-SC",  "Stephon Castle",           "San Antonio Spurs"),
    ("BCA-SGA", "Shai Gilgeous-Alexander",  "Oklahoma City Thunder"),
    ("BCA-SH",  "Scoot Henderson",          "Portland Trail Blazers"),
    ("BCA-SJ",  "Sion James",               "Charlotte Hornets"),
    ("BCA-SU",  "Stephen Curry",            "Golden State Warriors"),
    ("BCA-TE",  "Taelon Peter",             "Indiana Pacers"),
    ("BCA-TP",  "Tyrese Proctor",           "Cleveland Cavaliers"),
    ("BCA-TS",  "Thomas Sorber",            "Oklahoma City Thunder"),
    ("BCA-TSJ", "Terrence Shannon Jr.",     "Minnesota Timberwolves"),
    ("BCA-VW",  "Victor Wembanyama",        "San Antonio Spurs"),
    ("BCA-WC",  "Walter Clayton Jr.",       "Utah Jazz"),
    ("BCA-WI",  "Will Richard",             "Golden State Warriors"),
    ("BCA-WR",  "Will Riley",               "Washington Wizards"),
    ("BCA-YH",  "Yang Hansen",              "Portland Trail Blazers"),
    ("BCA-YK",  "Yanic Konan-Niederhäuser", "Los Angeles Clippers"),
    ("BCA-ZE",  "Zach Edey",                "Memphis Grizzlies"),
    ("BCA-ZR",  "Zaccharie Risacher",       "Atlanta Hawks"),
]

# Future Script Autographs (25 cards)
FUTURE_SCRIPT = [
    ("FS-AD",  "AJ Dybantsa",       "BYU"),
    ("FS-AL",  "Acaden Lewis",      "Villanova"),
    ("FS-BC",  "Brynn McGaughy",    "Washington"),
    ("FS-BM",  "Boopie Miller",     "SMU"),
    ("FS-BT",  "Bryson Tiller",     "Kansas"),
    ("FS-CW",  "Caleb Wilson",      "UNC"),
    ("FS-DP",  "Darryn Peterson",   "Kansas"),
    ("FS-IH",  "Isiah Harwell",     "Houston"),
    ("FS-JD",  "Josh Dix",          "Creighton"),
    ("FS-JE",  "Jason Edwards",     "Providence"),
    ("FS-JJ",  "Jasper Johnson",    "Kentucky"),
    ("FS-KA",  "Kiyan Anthony",     "Syracuse"),
    ("FS-KC",  "Kaelyn Carroll",    "Kentucky"),
    ("FS-KP",  "Koa Peat",          "Arizona"),
    ("FS-MB",  "Madison Booker",    "Texas"),
    ("FS-MBJ", "Mikel Brown Jr.",   "Louisville"),
    ("FS-MU",  "Milos Uzan",        "Houston"),
    ("FS-NA",  "Nate Ament",        "Tennessee"),
    ("FS-NB",  "Niko Bundalo",      "Ole Miss"),
    ("FS-OA",  "Obi Agbim",         "Baylor"),
    ("FS-RC",  "Ryan Conwell",      "Louisville"),
    ("FS-SA",  "Shon Abaev",        "Cincinnati"),
    ("FS-SB",  "Sienna Betts",      "UCLA"),
    ("FS-SH",  "Shelton Henderson", "Miami"),
    ("FS-TY",  "Tounde Yessoufou",  "Baylor"),
]

BUZZ_FACTOR = [
    ("BZA-AC", "Aaliyah Crump",       "Texas"),
    ("BZA-AM", "Agot Makeer",         "South Carolina"),
    ("BZA-BS", "Braeden Shrewsberry", "Notre Dame"),
    ("BZA-CC", "Coen Carr",           "Michigan State"),
    ("BZA-CM", "Cotie McMahon",       "Ole Miss"),
    ("BZA-DA", "Dwayne Aristode",     "Arizona"),
    ("BZA-DD", "Derek Dixon",         "UNC"),
    ("BZA-DW", "Darrion Williams",    "NC State"),
    ("BZA-HS", "Hailee Swain",        "Stanford"),
    ("BZA-JL", "Jaland Lowe",         "Kentucky"),
    ("BZA-KM", "Kiyomi McMiller",     "Penn State"),
    ("BZA-KR", "Kohl Rosario",        "Kansas"),
    ("BZA-KW", "Kam Williams",        "Kentucky"),
    ("BZA-MA", "Michael Rataj",       "Baylor"),
    ("BZA-MR", "Malik Reneau",        "Miami"),
    ("BZA-OO", "Otega Oweh",          "Kentucky"),
    ("BZA-RB", "Reed Bailey",         "Indiana"),
    ("BZA-SD", "Silas Demary Jr.",    "UConn"),
    ("BZA-SS", "Sarah Strong",        "UConn"),
    ("BZA-SW", "Serah Williams",      "UConn"),
    ("BZA-TD", "Tre Donaldson",       "Miami"),
    ("BZA-TJ", "Tylis Jordan",        "Ole Miss"),
    ("BZA-TK", "Trey Kaufman-Renn",   "Purdue"),
    ("BZA-XL", "Xaivian Lee",         "Florida"),
    ("BZA-ZE", "Zuby Ejiofor",        "St. John's"),
]

OPENING_STATEMENT = [
    ("OS-AB",  "Ace Bailey",            "Utah Jazz"),
    ("OS-AT",  "Alex Toohey",           "Golden State Warriors"),
    ("OS-BB",  "Brooks Barnhizer",      "Oklahoma City Thunder"),
    ("OS-CC",  "Cedric Coward",         "Memphis Grizzlies"),
    ("OS-CF",  "Cooper Flagg",          "Dallas Mavericks"),
    ("OS-CMB", "Collin Murray-Boyles",  "Toronto Raptors"),
    ("OS-DH",  "Dylan Harper",          "San Antonio Spurs"),
    ("OS-DQ",  "Derik Queen",           "New Orleans Pelicans"),
    ("OS-ED",  "Egor Dëmin",            "Brooklyn Nets"),
    ("OS-JM",  "Jahmai Mashack",        "Memphis Grizzlies"),
    ("OS-JS",  "Javon Small",           "Memphis Grizzlies"),
    ("OS-JT",  "John Tonje",            "Utah Jazz"),
    ("OS-JW",  "Jamir Watkins",         "Washington Wizards"),
    ("OS-KK",  "Kon Knueppel",          "Charlotte Hornets"),
    ("OS-KM",  "Khaman Maluach",        "Phoenix Suns"),
    ("OS-KS",  "Kobe Sanders",          "Los Angeles Clippers"),
    ("OS-LO",  "Lachlan Olbrich",       "Chicago Bulls"),
    ("OS-MR",  "Maxime Raynaud",        "Sacramento Kings"),
    ("OS-MS",  "Max Shulga",            "Boston Celtics"),
    ("OS-NE",  "Noa Essengue",          "Chicago Bulls"),
    ("OS-NP",  "Noah Penda",            "Orlando Magic"),
    ("OS-TE",  "Taelon Peter",          "Indiana Pacers"),
    ("OS-TP",  "Tyrese Proctor",        "Cleveland Cavaliers"),
    ("OS-WR",  "Will Richard",          "Golden State Warriors"),
    ("OS-YH",  "Yang Hansen",           "Portland Trail Blazers"),
]

TIMELESS_TOUCH = [
    ("TTA-AB", "Anthony Black",       "Orlando Magic"),
    ("TTA-AS", "Alex Sarr",           "Washington Wizards"),
    ("TTA-BM", "Brandon Miller",      "Charlotte Hornets"),
    ("TTA-CC", "Cade Cunningham",     "Detroit Pistons"),
    ("TTA-CH", "Cam Whitmore",        "Houston Rockets"),
    ("TTA-CL", "Cason Wallace",       "Oklahoma City Thunder"),
    ("TTA-CW", "Cody Williams",       "Utah Jazz"),
    ("TTA-DC", "Moses Moody",         "Golden State Warriors"),
    ("TTA-DD", "Dyson Daniels",       "Atlanta Hawks"),
    ("TTA-DT", "Dalen Terry",         "Chicago Bulls"),
    ("TTA-GD", "Gradey Dick",         "Toronto Raptors"),
    ("TTA-HT", "Tyrese Haliburton",   "Indiana Pacers"),
    ("TTA-IH", "Isaiah Hartenstein",  "Oklahoma City Thunder"),
    ("TTA-JH", "Jordan Hawkins",      "New Orleans Pelicans"),
    ("TTA-JI", "Jalen Williams",      "Oklahoma City Thunder"),
    ("TTA-JW", "Jarace Walker",       "Indiana Pacers"),
    ("TTA-OI", "Oso Ighodaro",        "Phoenix Suns"),
    ("TTA-RD", "Ryan Dunn",           "Phoenix Suns"),
    ("TTA-RG", "Rudy Gobert",         "Minnesota Timberwolves"),
    ("TTA-SH", "Scoot Henderson",     "Portland Trail Blazers"),
    ("TTA-TH", "Taylor Hendricks",    "Utah Jazz"),
    ("TTA-TS", "Tyler Smith",         "Milwaukee Bucks"),
    ("TTA-VW", "Victor Wembanyama",   "San Antonio Spurs"),
    ("TTA-ZE", "Zach Edey",           "Memphis Grizzlies"),
    ("TTA-ZR", "Zaccharie Risacher",  "Atlanta Hawks"),
]

# Paper Prospect Retail Autographs (100)
PAPER_PROSPECT_AUTOS = [
    ("PA-AC",  "Aaliyah Crump",       "Texas"),
    ("PA-AD",  "Addison Deal",        "Iowa"),
    ("PA-AE",  "Alexandra Eschmeyer", "Stanford"),
    ("PA-AF",  "Ace Flagg",           "Maine"),
    ("PA-AL",  "Acaden Lewis",        "Villanova"),
    ("PA-AM",  "Aliyahna Morris",     "California"),
    ("PA-AW",  "Ayla McDowell",       "South Carolina"),
    ("PA-AY",  "AJ Dybantsa",         "BYU"),
    ("PA-BB",  "Brayden Burries",     "Arizona"),
    ("PA-BG",  "Brandon Garrison",    "Kentucky"),
    ("PA-BI",  "Boopie Miller",       "SMU"),
    ("PA-BL",  "Bryce Lindsay",       "Villanova"),
    ("PA-BM",  "Brynn McGaughy",      "Washington"),
    ("PA-BR",  "Braden Smith",        "Purdue"),
    ("PA-BS",  "Braeden Shrewsberry", "Notre Dame"),
    ("PA-BT",  "Bennett Stirtz",      "Iowa"),
    ("PA-CA",  "Christian Anderson",  "Texas Tech"),
    ("PA-CC",  "Coen Carr",           "Michigan State"),
    ("PA-CF",  "Caleb Foster",        "Duke"),
    ("PA-CI",  "CJ Ingram",           "Florida"),
    ("PA-CL",  "Caleb Wilson",        "UNC"),
    ("PA-CM",  "Cotie McMahon",       "Ole Miss"),
    ("PA-CR",  "Chase Ross",          "Marquette"),
    ("PA-CW",  "Cam Ward",            "Michigan State"),
    ("PA-DA",  "Darianna Alexander",  "Cincinnati"),
    ("PA-DD",  "Derek Dixon",         "UNC"),
    ("PA-DE",  "Darryn Peterson",     "Kansas"),
    ("PA-DF",  "Davis Fogle",         "Gonzaga"),
    ("PA-DH",  "Davion Hannah",       "Alabama"),
    ("PA-DHJ", "Donald Hand Jr.",     "Boston College"),
    ("PA-DM",  "Devin McGlockton",    "Vanderbilt"),
    ("PA-DP",  "Deniya Prawl",        "Tennessee"),
    ("PA-DW",  "Darrion Williams",    "NC State"),
    ("PA-ES",  "Emilee Skinner",      "Duke"),
    ("PA-GK",  "Grace Knox",          "LSU"),
    ("PA-HS",  "Hailee Swain",        "Stanford"),
    ("PA-ID",  "Isaiah Denis",        "UNC"),
    ("PA-JB",  "John Blackwell",      "Wisconsin"),
    ("PA-JC",  "Jaida Civil",         "Tennessee"),
    ("PA-JD",  "Josh Dix",            "Creighton"),
    ("PA-JE",  "Jason Edwards",       "Providence"),
    ("PA-JG",  "Joe Grahovac",        "St. Bonaventure"),
    ("PA-JJ",  "Jamier Jones",        "Providence"),
    ("PA-JK",  "Ja'Kobi Gillespie",   "Tennessee"),
    ("PA-JL",  "Jaland Lowe",         "Kentucky"),
    ("PA-JT",  "JT Toppin",           "Texas Tech"),
    ("PA-JU",  "Juju Watkins",        "USC"),
    ("PA-JW",  "Jeremiah Wilkinson",  "Georgia"),
    ("PA-KC",  "Kaelyn Carroll",      "Kentucky"),
    ("PA-KD",  "Kara Dunn",           "USC"),
    ("PA-KF",  "Kelis Fisher",        "UConn"),
    ("PA-KH",  "Keyshawn Hall",       "Auburn"),
    ("PA-KM",  "Kiyomi McMiller",     "Penn State"),
    ("PA-KR",  "Kohl Rosario",        "Kansas"),
    ("PA-KS",  "Kaylene Smikle",      "Maryland"),
    ("PA-LM",  "Leah Macy",           "Notre Dame"),
    ("PA-LS",  "Lara Somfai",         "Stanford"),
    ("PA-MA",  "Michael Rataj",       "Baylor"),
    ("PA-MB",  "Madison Booker",      "Texas"),
    ("PA-MBJ", "Mikel Brown Jr.",     "Louisville"),
    ("PA-MK",  "Agot Makeer",         "South Carolina"),
    ("PA-MR",  "Kam Williams",        "Kentucky"),
    ("PA-MU",  "Milos Uzan",          "Houston"),
    ("PA-NB",  "Niko Bundalo",        "Ole Miss"),
    ("PA-NC",  "Nate Calmese",        "Wake Forest"),
    ("PA-NI",  "Nate Bittle",         "Oregon"),
    ("PA-NM",  "Nick Martinelli",     "Northwestern"),
    ("PA-NR",  "Nyla Brooks",         "UNC"),
    ("PA-OA",  "Obi Agbim",           "Baylor"),
    ("PA-OO",  "Otega Oweh",          "Kentucky"),
    ("PA-OR",  "Owen Freeman",        "Creighton"),
    ("PA-OS",  "Oziyah Sellers",      "St. John's"),
    ("PA-PP",  "Pharrel Payne",       "Maryland"),
    ("PA-RB",  "Reed Bailey",         "Indiana"),
    ("PA-RC",  "Ryan Conwell",        "Louisville"),
    ("PA-RE",  "Raegan Beers",        "Oklahoma"),
    ("PA-RM",  "Tre Donaldson",       "Miami"),
    ("PA-RS",  "Richie Saunders",     "BYU"),
    ("PA-SA",  "Shon Abaev",          "Cincinnati"),
    ("PA-SB",  "Sienna Betts",        "UCLA"),
    ("PA-SD",  "Silas Demary Jr.",    "UConn"),
    ("PA-SH",  "Sadiq White",         "Syracuse"),
    ("PA-SI",  "Sebastian Wilkins",   "Duke"),
    ("PA-SS",  "Sarah Strong",        "UConn"),
    ("PA-SW",  "Serah Williams",      "UConn"),
    ("PA-TA",  "Tobe Awaka",          "Arizona"),
    ("PA-TD",  "Malik Reneau",        "Miami"),
    ("PA-TH",  "Tre Holloman",        "NC State"),
    ("PA-TJ",  "Robert McCray V",     "Florida State"),
    ("PA-TKR", "Trey Kaufman-Renn",   "Purdue"),
    ("PA-TL",  "Ta'Niya Latson",      "South Carolina"),
    ("PA-TO",  "Tylis Jordan",        "Ole Miss"),
    ("PA-TR",  "Tarris Reed Jr.",     "UConn"),
    ("PA-TY",  "Tounde Yessoufou",    "Baylor"),
    ("PA-WG",  "Winters Grady",       "Michigan"),
    ("PA-WY",  "Wesley Yates III",    "Washington"),
    ("PA-XL",  "Xaivian Lee",         "Florida"),
    ("PA-YG",  "Yarden Garzon",       "Maryland"),
    ("PA-ZE",  "Zuby Ejiofor",        "St. John's"),
    ("PA-ZJ",  "ZaKiyah Johnson",     "LSU"),
]

# Paper Rookies & Veterans (99)
PAPER_RV_AUTOS = [
    ("RVA-AB",  "Ace Bailey",                "Utah Jazz"),
    ("RVA-AH",  "Al Horford",                "Boston Celtics"),
    ("RVA-AL",  "Anthony Black",             "Orlando Magic"),
    ("RVA-AM",  "Alijah Martin",             "Toronto Raptors"),
    ("RVA-AN",  "Asa Newell",                "Atlanta Hawks"),
    ("RVA-AO",  "Alex Toohey",               "Golden State Warriors"),
    ("RVA-AT",  "Adou Thiero",               "Los Angeles Lakers"),
    ("RVA-BB",  "Brooks Barnhizer",          "Oklahoma City Thunder"),
    ("RVA-BC",  "Brandon Clarke",            "Memphis Grizzlies"),
    ("RVA-BS",  "Ben Saraf",                 "Brooklyn Nets"),
    ("RVA-BSC", "Baylor Scheierman",         "Boston Celtics"),
    ("RVA-CC",  "Cedric Coward",             "Memphis Grizzlies"),
    ("RVA-CF",  "Cooper Flagg",              "Dallas Mavericks"),
    ("RVA-CH",  "Chet Holmgren",             "Oklahoma City Thunder"),
    ("RVA-CL",  "Chaz Lanier",               "Detroit Pistons"),
    ("RVA-CMB", "Collin Murray-Boyles",      "Toronto Raptors"),
    ("RVA-CW",  "Cody Williams",             "Utah Jazz"),
    ("RVA-CWA", "Cason Wallace",             "Oklahoma City Thunder"),
    ("RVA-CWH", "Cam Whitmore",              "Houston Rockets"),
    ("RVA-DA",  "Deandre Ayton",             "Portland Trail Blazers"),
    ("RVA-DC",  "Devin Carter",              "Sacramento Kings"),
    ("RVA-DH",  "Dylan Harper",              "San Antonio Spurs"),
    ("RVA-DJ",  "Dillon Jones",              "Oklahoma City Thunder"),
    ("RVA-DP",  "Drake Powell",              "Brooklyn Nets"),
    ("RVA-DQ",  "Derik Queen",               "New Orleans Pelicans"),
    ("RVA-DT",  "Derrick White",             "Boston Celtics"),
    ("RVA-DW",  "Danny Wolf",                "Brooklyn Nets"),
    ("RVA-ED",  "Egor Dëmin",                "Brooklyn Nets"),
    ("RVA-FW",  "Franz Wagner",              "Orlando Magic"),
    ("RVA-GD",  "Gradey Dick",               "Toronto Raptors"),
    ("RVA-IC",  "Isaiah Collier",            "Utah Jazz"),
    ("RVA-JA",  "Jarrett Allen",             "Cleveland Cavaliers"),
    ("RVA-JB",  "Johni Broome",              "Philadelphia 76ers"),
    ("RVA-JBE", "Joan Beringer",             "Minnesota Timberwolves"),
    ("RVA-JBR", "Jalen Brunson",             "New York Knicks"),
    ("RVA-JC",  "Jeremy Sochan",             "San Antonio Spurs"),
    ("RVA-JD",  "Jett Howard",               "Orlando Magic"),
    ("RVA-JF",  "Johnny Furphy",             "Indiana Pacers"),
    ("RVA-JH",  "Jrue Holiday",              "Boston Celtics"),
    ("RVA-JHS", "Jaime Jaquez Jr.",          "Miami Heat"),
    ("RVA-JI",  "Jalen Williams",            "Oklahoma City Thunder"),
    ("RVA-JK",  "Jarace Walker",             "Indiana Pacers"),
    ("RVA-JL",  "Jaylin Williams",           "Oklahoma City Thunder"),
    ("RVA-JM",  "Jahmai Mashack",            "Memphis Grizzlies"),
    ("RVA-JN",  "James Harden",              "Los Angeles Clippers"),
    ("RVA-JR",  "Jase Richardson",           "Orlando Magic"),
    ("RVA-JS",  "Javon Small",               "Memphis Grizzlies"),
    ("RVA-JT",  "John Tonje",                "Utah Jazz"),
    ("RVA-JU",  "Jamal Murray",              "Denver Nuggets"),
    ("RVA-JW",  "Jamir Watkins",             "Washington Wizards"),
    ("RVA-KB",  "Koby Brea",                 "Phoenix Suns"),
    ("RVA-KF",  "Kyle Filipowski",           "Utah Jazz"),
    ("RVA-KJ",  "Kasparas Jakučionis",       "Miami Heat"),
    ("RVA-KK",  "Kon Knueppel",              "Charlotte Hornets"),
    ("RVA-KM",  "Khaman Maluach",            "Phoenix Suns"),
    ("RVA-KO",  "Kam Jones",                 "Indiana Pacers"),
    ("RVA-KS",  "Kobe Sanders",              "Los Angeles Clippers"),
    ("RVA-KW",  "Kel'el Ware",               "Miami Heat"),
    ("RVA-LM",  "Liam McNeeley",             "Charlotte Hornets"),
    ("RVA-LO",  "Lachlan Olbrich",           "Chicago Bulls"),
    ("RVA-MM",  "Miles McBride",             "New York Knicks"),
    ("RVA-MP",  "Micah Peavy",               "New Orleans Pelicans"),
    ("RVA-MR",  "Maxime Raynaud",            "Sacramento Kings"),
    ("RVA-MS",  "Max Shulga",                "Boston Celtics"),
    ("RVA-NC",  "Nique Clifford",            "Sacramento Kings"),
    ("RVA-NE",  "Noa Essengue",              "Chicago Bulls"),
    ("RVA-NJ",  "Nikola Jović",              "Miami Heat"),
    ("RVA-NP",  "Noah Penda",                "Orlando Magic"),
    ("RVA-NT",  "Nolan Traore",              "Brooklyn Nets"),
    ("RVA-PB",  "Paolo Banchero",            "Orlando Magic"),
    ("RVA-PD",  "Pacôme Dadiet",             "New York Knicks"),
    ("RVA-QP",  "Quinten Post",              "Golden State Warriors"),
    ("RVA-RD",  "Ryan Dunn",                 "Phoenix Suns"),
    ("RVA-RF",  "Rasheer Fleming",           "Phoenix Suns"),
    ("RVA-RH",  "Ron Holland II",            "Detroit Pistons"),
    ("RVA-RI",  "Rob Dillingham",            "Minnesota Timberwolves"),
    ("RVA-RK",  "Ryan Kalkbrenner",          "Charlotte Hornets"),
    ("RVA-RO",  "Royce O'Neale",             "Phoenix Suns"),
    ("RVA-SC",  "Stephon Castle",            "San Antonio Spurs"),
    ("RVA-SH",  "Scoot Henderson",           "Portland Trail Blazers"),
    ("RVA-SJ",  "Sion James",                "Charlotte Hornets"),
    ("RVA-TA",  "Tidjane Salaün",            "Charlotte Hornets"),
    ("RVA-TD",  "Tristan da Silva",          "Orlando Magic"),
    ("RVA-TE",  "Taelon Peter",              "Indiana Pacers"),
    ("RVA-TH",  "Taylor Hendricks",          "Utah Jazz"),
    ("RVA-TI",  "Tyler Smith",               "Milwaukee Bucks"),
    ("RVA-TK",  "Tyler Kolek",               "New York Knicks"),
    ("RVA-TM",  "Terance Mann",              "Atlanta Hawks"),
    ("RVA-TP",  "Tyrese Proctor",            "Cleveland Cavaliers"),
    ("RVA-TS",  "Thomas Sorber",             "Oklahoma City Thunder"),
    ("RVA-WC",  "Walter Clayton Jr.",        "Utah Jazz"),
    ("RVA-WI",  "Will Richard",              "Golden State Warriors"),
    ("RVA-WR",  "Will Riley",                "Washington Wizards"),
    ("RVA-XT",  "Xavier Tillman Sr.",        "Boston Celtics"),
    ("RVA-YH",  "Yang Hansen",               "Portland Trail Blazers"),
    ("RVA-YK",  "Yanic Konan-Niederhäuser",  "Los Angeles Clippers"),
    ("RVA-YM",  "Yves Missi",                "New Orleans Pelicans"),
    ("RVA-ZE",  "Zach Edey",                 "Memphis Grizzlies"),
    ("RVA-ZR",  "Zaccharie Risacher",        "Atlanta Hawks"),
]

# Bowman Dual Autographs (10)
DUAL_AUTOS = [
    ("BDA-AC",  "Grace Knox / Aaliyah Crump",       "LSU / Texas"),
    ("BDA-AD",  "Darryn Peterson / AJ Dybantsa",    "Kansas / BYU"),
    ("BDA-AY",  "AJ Dybantsa / Sienna Betts",       "BYU / UCLA"),
    ("BDA-CW",  "Caleb Wilson / AJ Dybantsa",       "UNC / BYU"),
    ("BDA-DP",  "Nate Ament / Darryn Peterson",     "Tennessee / Kansas"),
    ("BDA-JD",  "Darryn Peterson / Juju Watkins",   "Kansas / USC"),
    ("BDA-JW",  "Sienna Betts / Juju Watkins",      "UCLA / USC"),
    ("BDA-KA",  "Kiyan Anthony / Nate Ament",       "Syracuse / Tennessee"),
    ("BDA-SB",  "Emilee Skinner / Sienna Betts",    "Duke / UCLA"),
    ("BDPA-ST", "Raegan Beers / Sarah Strong",      "Oklahoma / UConn"),
]

# Insert sets — typically just a list of (number, player, team)
TALENT_TRACKER = [
    (1,  "AJ Dybantsa",        "BYU"),
    (2,  "Darryn Peterson",    "Kansas"),
    (3,  "Koa Peat",           "Arizona"),
    (4,  "Emilee Skinner",     "Duke"),
    (5,  "Sarah Strong",       "UConn"),
    (6,  "Sienna Betts",       "UCLA"),
    (7,  "Raegan Beers",       "Oklahoma"),
    (8,  "Juju Watkins",       "USC"),
    (9,  "Caleb Wilson",       "UNC"),
    (10, "Nate Ament",         "Tennessee"),
    (11, "Mikel Brown Jr.",    "Louisville"),
    (12, "Aaliyah Crump",      "Texas"),
    (13, "Hailee Swain",       "Stanford"),
    (14, "Bennett Stirtz",     "Iowa"),
    (15, "Otega Oweh",         "Kentucky"),
    (16, "Caleb Foster",       "Duke"),
    (17, "ZaKiyah Johnson",    "LSU"),
    (18, "Leah Macy",          "Notre Dame"),
    (19, "Richie Saunders",    "BYU"),
    (20, "Kohl Rosario",       "Kansas"),
    (21, "JT Toppin",          "Texas Tech"),
    (22, "Braden Smith",       "Purdue"),
    (23, "Jaida Civil",        "Tennessee"),
    (24, "Addison Deal",       "Iowa"),
    (25, "Milos Uzan",         "Houston"),
]

GEN_NEXT = [
    (1,  "AJ Dybantsa",        "BYU"),
    (2,  "Darryn Peterson",    "Kansas"),
    (3,  "Koa Peat",           "Arizona"),
    (4,  "Emilee Skinner",     "Duke"),
    (5,  "Sarah Strong",       "UConn"),
    (6,  "Sienna Betts",       "UCLA"),
    (7,  "Raegan Beers",       "Oklahoma"),
    (8,  "Juju Watkins",       "USC"),
    (9,  "Caleb Wilson",       "UNC"),
    (10, "Nate Ament",         "Tennessee"),
    (11, "Mikel Brown Jr.",    "Louisville"),
    (12, "Aaliyah Crump",      "Texas"),
    (13, "Sebastian Wilkins",  "Duke"),
    (14, "JT Toppin",          "Texas Tech"),
    (15, "Braden Smith",       "Purdue"),
    (16, "Ta'Niya Latson",     "South Carolina"),
    (17, "Zuby Ejiofor",       "St. John's"),
    (18, "Davis Fogle",        "Gonzaga"),
    (19, "Grace Knox",         "LSU"),
    (20, "Madison Booker",     "Texas"),
    (21, "Nate Calmese",       "Wake Forest"),
    (22, "Tobe Awaka",         "Arizona"),
    (23, "Richie Saunders",    "BYU"),
    (24, "Winters Grady",      "Michigan"),
    (25, "Deniya Prawl",       "Tennessee"),
]

VIP = [
    (1,  "AJ Dybantsa",        "BYU"),
    (2,  "Darryn Peterson",    "Kansas"),
    (3,  "Koa Peat",           "Arizona"),
    (4,  "Emilee Skinner",     "Duke"),
    (5,  "Sarah Strong",       "UConn"),
    (6,  "Sienna Betts",       "UCLA"),
    (7,  "Raegan Beers",       "Oklahoma"),
    (8,  "Juju Watkins",       "USC"),
    (9,  "Caleb Wilson",       "UNC"),
    (10, "Nate Ament",         "Tennessee"),
    (11, "Mikel Brown Jr.",    "Louisville"),
    (12, "Aaliyah Crump",      "Texas"),
    (13, "Kara Dunn",          "USC"),
    (14, "Boopie Miller",      "SMU"),
    (15, "ZaKiyah Johnson",    "LSU"),
    (16, "Jaida Civil",        "Tennessee"),
    (17, "Alexandra Eschmeyer","Stanford"),
    (18, "Aliyahna Morris",    "California"),
    (19, "Tounde Yessoufou",   "Baylor"),
    (20, "Brynn McGaughy",     "Washington"),
    (21, "Obi Agbim",          "Baylor"),
    (22, "Ta'Niya Latson",     "South Carolina"),
    (23, "Trey Kaufman-Renn",  "Purdue"),
    (24, "Zuby Ejiofor",       "St. John's"),
    (25, "Joe Grahovac",       "St. Bonaventure"),
]

BOWMAN_VERIFIED = [
    (1,  "AJ Dybantsa",        "BYU"),
    (2,  "Darryn Peterson",    "Kansas"),
    (3,  "Koa Peat",           "Arizona"),
    (4,  "Emilee Skinner",     "Duke"),
    (5,  "Sarah Strong",       "UConn"),
    (6,  "Sienna Betts",       "UCLA"),
    (7,  "Raegan Beers",       "Oklahoma"),
    (8,  "Juju Watkins",       "USC"),
    (9,  "Caleb Wilson",       "UNC"),
    (10, "Nate Ament",         "Tennessee"),
    (11, "Mikel Brown Jr.",    "Louisville"),
    (12, "Aaliyah Crump",      "Texas"),
    (13, "Ryan Conwell",       "Louisville"),
    (14, "Kam Williams",       "Kentucky"),
    (15, "JT Toppin",          "Texas Tech"),
    (16, "Braden Smith",       "Purdue"),
    (17, "Kohl Rosario",       "Kansas"),
    (18, "Ta'Niya Latson",     "South Carolina"),
    (19, "Oziyah Sellers",     "St. John's"),
    (20, "Ayla McDowell",      "South Carolina"),
    (21, "ZaKiyah Johnson",    "LSU"),
    (22, "Jaida Civil",        "Tennessee"),
    (23, "Alexandra Eschmeyer","Stanford"),
    (24, "Bryce Lindsay",      "Villanova"),
    (25, "Cam Ward",           "Michigan State"),
]

ROY_FAVORITES = [
    (1,  "Cooper Flagg",         "Dallas Mavericks"),
    (2,  "Dylan Harper",         "San Antonio Spurs"),
    (3,  "VJ Edgecombe",         "Philadelphia 76ers"),
    (4,  "Kon Knueppel",         "Charlotte Hornets"),
    (5,  "Ace Bailey",           "Utah Jazz"),
    (6,  "Tre Johnson III",      "Washington Wizards"),
    (7,  "Jeremiah Fears",       "New Orleans Pelicans"),
    (8,  "Egor Dëmin",           "Brooklyn Nets"),
    (9,  "Collin Murray-Boyles", "Toronto Raptors"),
    (10, "Khaman Maluach",       "Phoenix Suns"),
    (11, "Cedric Coward",        "Memphis Grizzlies"),
    (12, "Kasparas Jakučionis",  "Miami Heat"),
    (13, "Derik Queen",          "New Orleans Pelicans"),
    (14, "Carter Bryant",        "San Antonio Spurs"),
    (15, "Yang Hansen",          "Portland Trail Blazers"),
]

HOBBY_STARS = [
    (1,  "Paolo Banchero",       "Orlando Magic"),
    (2,  "Stephen Curry",        "Golden State Warriors"),
    (3,  "Cooper Flagg",         "Dallas Mavericks"),
    (4,  "Dylan Harper",         "San Antonio Spurs"),
    (5,  "Donovan Mitchell",     "Cleveland Cavaliers"),
    (6,  "Tyrese Haliburton",    "Indiana Pacers"),
    (7,  "Kon Knueppel",         "Charlotte Hornets"),
    (8,  "VJ Edgecombe",         "Philadelphia 76ers"),
    (9,  "Ace Bailey",           "Utah Jazz"),
    (10, "Jayson Tatum",         "Boston Celtics"),
    (11, "Jalen Brunson",        "New York Knicks"),
    (12, "Kevin Durant",         "Houston Rockets"),
    (13, "LeBron James",         "Los Angeles Lakers"),
    (14, "Anthony Edwards",      "Minnesota Timberwolves"),
    (15, "Victor Wembanyama",    "San Antonio Spurs"),
]

YOUNG_KINGS = [
    (1,  "Shai Gilgeous-Alexander", "Los Angeles Clippers"),
    (2,  "Luka Dončić",             "Dallas Mavericks"),
    (3,  "Tyrese Haliburton",       "Sacramento Kings"),
    (4,  "Stephen Curry",           "Golden State Warriors"),
    (5,  "LeBron James",            "Cleveland Cavaliers"),
    (6,  "Nikola Jokić",            "Denver Nuggets"),
    (7,  "Ja Morant",               "Memphis Grizzlies"),
    (8,  "Victor Wembanyama",       "San Antonio Spurs"),
    (9,  "James Harden",            "Oklahoma City Thunder"),
    (10, "Kawhi Leonard",           "San Antonio Spurs"),
    (11, "Jimmy Butler III",        "Chicago Bulls"),
    (12, "Cade Cunningham",         "Detroit Pistons"),
    (13, "Devin Booker",            "Phoenix Suns"),
    (14, "Kevin Durant",            "Oklahoma City Thunder"),
    (15, "Donovan Mitchell",        "Utah Jazz"),
    (16, "Allen Iverson",           "Philadelphia 76ers"),
    (17, "Larry Bird",              "Boston Celtics"),
    (18, "Magic Johnson",           "Los Angeles Lakers"),
    (19, "Shaquille O'Neal",        "Los Angeles Lakers"),
    (20, "Dirk Nowitzki",           "Dallas Mavericks"),
    (21, "Kevin Garnett",           "Minnesota Timberwolves"),
    (22, "Carmelo Anthony",         "Denver Nuggets"),
    (23, "Dwyane Wade",             "Miami Heat"),
    (24, "Tracy McGrady",           "Toronto Raptors"),
    (25, "Ray Allen",               "Seattle Supersonics"),
]

ROCKSTAR_ROOKIES = [
    (i, p, t) for i, (p, t) in enumerate(
        [(BASE_200[i-1][1], BASE_200[i-1][2]) for i in range(1, 21)],
        start=1,
    )
]

# Greatness Loading uses cards 1-25 of base
GREATNESS_LOADING = [
    (i, BASE_200[i-1][1], BASE_200[i-1][2]) for i in range(1, 26)
]

MEGA_ROOKIES = [
    (i, BASE_200[i-1][1], BASE_200[i-1][2]) for i in range(1, 25)
] + [(25, "Danny Wolf", "Brooklyn Nets")]

MEGA_PROSPECTS = [
    (1,  "AJ Dybantsa",          "BYU"),
    (2,  "Darryn Peterson",      "Kansas"),
    (3,  "Koa Peat",             "Arizona"),
    (4,  "Emilee Skinner",       "Duke"),
    (5,  "Sarah Strong",         "UConn"),
    (6,  "Sienna Betts",         "UCLA"),
    (7,  "Raegan Beers",         "Oklahoma"),
    (8,  "Juju Watkins",         "USC"),
    (9,  "Caleb Wilson",         "UNC"),
    (10, "Nate Ament",           "Tennessee"),
    (11, "Otega Oweh",           "Kentucky"),
    (12, "Sebastian Wilkins",    "Duke"),
    (13, "Hailee Swain",         "Stanford"),
    (14, "Kaylene Smikle",       "Maryland"),
    (15, "Milos Uzan",           "Houston"),
    (16, "Sadiq White",          "Syracuse"),
    (17, "Tarris Reed Jr.",      "UConn"),
    (18, "Wesley Yates III",     "Washington"),
    (19, "Lara Somfai",          "Stanford"),
    (20, "Christian Anderson",   "Texas Tech"),
    (21, "Davion Hannah",        "Alabama"),
    (22, "Davis Fogle",          "Gonzaga"),
    (23, "Grace Knox",           "LSU"),
    (24, "Isaiah Denis",         "UNC"),
    (25, "Addison Deal",         "Iowa"),
]

SPOTLIGHTS_NBA = [
    ("BNB-1",  "Cooper Flagg",        "Dallas Mavericks"),
    ("BNB-2",  "Dylan Harper",        "San Antonio Spurs"),
    ("BNB-3",  "VJ Edgecombe",        "Philadelphia 76ers"),
    ("BNB-4",  "Kon Knueppel",        "Charlotte Hornets"),
    ("BNB-5",  "Ace Bailey",          "Utah Jazz"),
    ("BNB-6",  "Tre Johnson III",     "Washington Wizards"),
    ("BNB-7",  "LeBron James",        "Los Angeles Lakers"),
    ("BNB-8",  "Anthony Edwards",     "Minnesota Timberwolves"),
    ("BNB-9",  "Victor Wembanyama",   "San Antonio Spurs"),
    ("BNB-10", "Stephen Curry",       "Golden State Warriors"),
]

SPOTLIGHTS_NIL = [
    ("BNS-1", "AJ Dybantsa",      "BYU"),
    ("BNS-2", "Darryn Peterson",  "Kansas"),
    ("BNS-3", "Madison Booker",   "Texas"),
    ("BNS-4", "Juju Watkins",     "USC"),
    ("BNS-5", "Nate Ament",       "Tennessee"),
]

CRYSTALLIZED_NBA = [
    ("CNB-1",  "Cooper Flagg",          "Dallas Mavericks"),
    ("CNB-2",  "Dylan Harper",          "San Antonio Spurs"),
    ("CNB-3",  "VJ Edgecombe",          "Philadelphia 76ers"),
    ("CNB-4",  "Kon Knueppel",          "Charlotte Hornets"),
    ("CNB-5",  "Ace Bailey",            "Utah Jazz"),
    ("CNB-6",  "Jayson Tatum",          "Boston Celtics"),
    ("CNB-7",  "Stephen Curry",         "Golden State Warriors"),
    ("CNB-8",  "Giannis Antetokounmpo", "Milwaukee Bucks"),
    ("CNB-9",  "Anthony Edwards",       "Minnesota Timberwolves"),
    ("CNB-10", "Victor Wembanyama",     "San Antonio Spurs"),
]

CRYSTALLIZED_NIL = [
    ("CNL-1", "AJ Dybantsa",      "BYU"),
    ("CNL-2", "Darryn Peterson",  "Kansas"),
    ("CNL-3", "Sienna Betts",     "UCLA"),
    ("CNL-4", "Juju Watkins",     "USC"),
    ("CNL-5", "Nate Ament",       "Tennessee"),
]

ANIME_NBA = [
    ("NBA-A1",  "Jayson Tatum",            "Boston Celtics"),
    ("NBA-A2",  "Jalen Brunson",           "New York Knicks"),
    ("NBA-A3",  "Tyrese Maxey",            "Philadelphia 76ers"),
    ("NBA-A4",  "Cade Cunningham",         "Detroit Pistons"),
    ("NBA-A5",  "Tyrese Haliburton",       "Indiana Pacers"),
    ("NBA-A6",  "Giannis Antetokounmpo",   "Milwaukee Bucks"),
    ("NBA-A7",  "LaMelo Ball",             "Charlotte Hornets"),
    ("NBA-A8",  "Donovan Mitchell",        "Cleveland Cavaliers"),
    ("NBA-A9",  "Paolo Banchero",          "Orlando Magic"),
    ("NBA-A10", "Nikola Jokić",            "Denver Nuggets"),
    ("NBA-A11", "Anthony Edwards",         "Minnesota Timberwolves"),
    ("NBA-A12", "Shai Gilgeous-Alexander", "Oklahoma City Thunder"),
    ("NBA-A13", "Stephen Curry",           "Golden State Warriors"),
    ("NBA-A14", "Luka Dončić",             "Los Angeles Lakers"),
    ("NBA-A15", "LeBron James",            "Los Angeles Lakers"),
    ("NBA-A16", "Amen Thompson",           "Houston Rockets"),
    ("NBA-A17", "Victor Wembanyama",       "San Antonio Spurs"),
    ("NBA-A18", "Devin Booker",            "Phoenix Suns"),
    ("NBA-A19", "Cooper Flagg",            "Dallas Mavericks"),
    ("NBA-A20", "Dylan Harper",            "San Antonio Spurs"),
    ("NBA-A21", "VJ Edgecombe",            "Philadelphia 76ers"),
    ("NBA-A22", "Ace Bailey",              "Utah Jazz"),
    ("NBA-A23", "Jeremiah Fears",          "New Orleans Pelicans"),
    ("NBA-A24", "Kon Knueppel",            "Charlotte Hornets"),
    ("NBA-A25", "Tre Johnson III",         "Washington Wizards"),
]

ANIME_NIL = [
    ("NIL-A1", "AJ Dybantsa",      "BYU"),
    ("NIL-A2", "Darryn Peterson",  "Kansas"),
    ("NIL-A3", "Juju Watkins",     "USC"),
    ("NIL-A4", "Sienna Betts",     "UCLA"),
    ("NIL-A5", "Koa Peat",         "Arizona"),
]

GPK_NBA = [
    ("BGP-1", "Cooper Flagg",      "Dallas Mavericks"),
    ("BGP-2", "Ace Bailey",        "Utah Jazz"),
    ("BGP-3", "Dylan Harper",      "San Antonio Spurs"),
    ("BGP-4", "Kon Knueppel",      "Charlotte Hornets"),
    ("BGP-5", "Anthony Edwards",   "Minnesota Timberwolves"),
]

GPK_NIL = [
    ("BNIL-1", "Sienna Betts",     "UCLA"),
    ("BNIL-2", "Sarah Strong",     "UConn"),
    ("BNIL-3", "AJ Dybantsa",      "BYU"),
    ("BNIL-4", "Darryn Peterson",  "Kansas"),
]

# ---------------------------------------------------------------------------
# Helpers to build subset records
# ---------------------------------------------------------------------------

def card_base(num, player, team, prefix=""):
    return {
        "number":    f"{prefix}{num}" if prefix else str(num),
        "player":    player,
        "team":      team,
        "isRC":      is_rc_base(num) if not prefix else False,
    }

def card_with_id(num, player, team):
    return {
        "number": num,
        "player": player,
        "team":   team,
    }

# ---------------------------------------------------------------------------
# Build the set
# ---------------------------------------------------------------------------

subsets = []

# Base
subsets.append({
    "id": "base",
    "name": "Base",
    "cardPrefix": "",
    "cardCount": 200,
    "type": "base",
    "isAuto": False,
    "isInsert": False,
    "league": "NBA",
    "parallels": NBA_BASE_PAPER_PARALLELS,
    "cards": [card_base(n, p, t) for n, p, t in BASE_200],
})

# Base — Chrome
subsets.append({
    "id": "base-chrome",
    "name": "Base — Chrome",
    "cardPrefix": "BCV-",
    "cardCount": 200,
    "type": "chrome",
    "isAuto": False,
    "isInsert": False,
    "league": "NBA",
    "parallels": NBA_BASE_CHROME_PARALLELS,
    "cards": [
        {"number": f"BCV-{n}", "player": p, "team": t, "isRC": is_rc_base(n)}
        for n, p, t in BASE_200
    ],
})

# Red Rookie Variations
subsets.append({
    "id": "red-rookie-variations",
    "name": "Base — Red Rookie Variations",
    "cardCount": 50,
    "type": "variation",
    "isAuto": False,
    "isInsert": False,
    "league": "NBA",
    "parallels": [],  # has no separate parallel rainbow per article
    "cards": [{"number": num, "player": p, "team": t, "isRC": True} for num, p, t in RED_ROOKIES],
})

# Etched In Glass — Base
subsets.append({
    "id": "etched-in-glass-base",
    "name": "Base — Etched In Glass Variations",
    "cardCount": 10,
    "type": "variation",
    "isAuto": False,
    "isInsert": False,
    "league": "NBA",
    "parallels": GLASS_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in ETCHED_GLASS_BASE],
})

# Retrofractor Variations (base)
subsets.append({
    "id": "retrofractor-variations",
    "name": "Retrofractor Variations",
    "cardCount": 2,
    "type": "variation",
    "isAuto": False,
    "isInsert": False,
    "league": "Vintage",
    "parallels": GLASS_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in RETROFRACTOR_BASE],
})

# Prospects — Paper
subsets.append({
    "id": "prospects",
    "name": "Prospects",
    "cardPrefix": "BPP-",
    "cardCount": 100,
    "type": "prospect",
    "isAuto": False,
    "isInsert": False,
    "league": "NCAA",
    "parallels": NBA_BASE_PAPER_PARALLELS,
    "cards": [{"number": f"BPP-{n}", "player": p, "team": t} for n, p, t in PROSPECTS_100],
})

# Prospects — Chrome
subsets.append({
    "id": "prospects-chrome",
    "name": "Chrome Prospects",
    "cardPrefix": "BCP-",
    "cardCount": 100,
    "type": "chrome-prospect",
    "isAuto": False,
    "isInsert": False,
    "league": "NCAA",
    "parallels": CHROME_PROSPECT_PARALLELS,
    "cards": [{"number": f"BCP-{n}", "player": p, "team": t} for n, p, t in PROSPECTS_100],
})

# Etched In Glass — Chrome Prospects
subsets.append({
    "id": "etched-in-glass-prospects",
    "name": "Chrome Prospects — Etched In Glass Variations",
    "cardCount": 5,
    "type": "variation",
    "isAuto": False,
    "isInsert": False,
    "league": "NCAA",
    "parallels": GLASS_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in ETCHED_GLASS_PROSPECTS],
})

# Chrome Prospect Autographs
subsets.append({
    "id": "chrome-prospect-autographs",
    "name": "Chrome Prospect Autographs",
    "cardPrefix": "CPA-",
    "cardCount": 101,
    "type": "auto",
    "isAuto": True,
    "isInsert": False,
    "league": "NCAA",
    "parallels": CHROME_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in CHROME_PROSPECT_AUTOS],
})

# Chrome Autographs (NBA)
subsets.append({
    "id": "chrome-autographs",
    "name": "Chrome Autographs",
    "cardPrefix": "BCA-",
    "cardCount": 98,
    "type": "auto",
    "isAuto": True,
    "isInsert": False,
    "league": "NBA",
    "parallels": CHROME_AUTO_PARALLELS_VET,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in CHROME_AUTOS_NBA],
})

# Retrofractor Auto
subsets.append({
    "id": "retrofractor-autographs",
    "name": "Retrofractor Autographs",
    "cardCount": 1,
    "type": "auto",
    "isAuto": True,
    "isInsert": False,
    "league": "Vintage",
    "parallels": PROMO_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in RETROFRACTOR_AUTO],
})

# Future Script
subsets.append({
    "id": "future-script",
    "name": "Future Script",
    "cardPrefix": "FS-",
    "cardCount": 25,
    "type": "auto",
    "isAuto": True,
    "isInsert": True,
    "league": "NCAA",
    "parallels": PROMO_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in FUTURE_SCRIPT],
})

# Buzz Factor
subsets.append({
    "id": "buzz-factor",
    "name": "Buzz Factor Autographs",
    "cardPrefix": "BZA-",
    "cardCount": 25,
    "type": "auto",
    "isAuto": True,
    "isInsert": True,
    "league": "NCAA",
    "parallels": PROMO_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in BUZZ_FACTOR],
})

# Opening Statement
subsets.append({
    "id": "opening-statement",
    "name": "Opening Statement Signatures",
    "cardPrefix": "OS-",
    "cardCount": 25,
    "type": "auto",
    "isAuto": True,
    "isInsert": True,
    "league": "NBA",
    "parallels": PROMO_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in OPENING_STATEMENT],
})

# Timeless Touch
subsets.append({
    "id": "timeless-touch",
    "name": "Timeless Touch Signatures",
    "cardPrefix": "TTA-",
    "cardCount": 25,
    "type": "auto",
    "isAuto": True,
    "isInsert": True,
    "league": "NBA",
    "parallels": PROMO_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in TIMELESS_TOUCH],
})

# Paper Prospect Retail Autos
subsets.append({
    "id": "paper-prospect-retail-autographs",
    "name": "Paper Prospect Retail Autographs",
    "cardPrefix": "PA-",
    "cardCount": 100,
    "type": "auto",
    "isAuto": True,
    "isInsert": False,
    "league": "NCAA",
    "parallels": PAPER_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in PAPER_PROSPECT_AUTOS],
})

# Paper Rookies & Veterans Retail Autos
subsets.append({
    "id": "paper-rv-retail-autographs",
    "name": "Paper Rookie And Veterans Retail Autographs",
    "cardPrefix": "RVA-",
    "cardCount": 99,
    "type": "auto",
    "isAuto": True,
    "isInsert": False,
    "league": "NBA",
    "parallels": PAPER_AUTO_PARALLELS,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in PAPER_RV_AUTOS],
})

# Bowman Dual Autographs
subsets.append({
    "id": "bowman-dual-autographs",
    "name": "Bowman Dual Autographs",
    "cardCount": 10,
    "type": "auto-dual",
    "isAuto": True,
    "isInsert": True,
    "league": "NCAA",
    "parallels": ["chrome-superfractor"],
    "baseSerialPrintRun": 10,
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in DUAL_AUTOS],
})

# ---- Inserts (common rainbow) ----

INSERT_SUBSET_DEFS = [
    ("talent-tracker",      "Talent Tracker",          "TT-",  TALENT_TRACKER, "NCAA"),
    ("gen-next",            "Gen Next",                "GN-",  GEN_NEXT,       "NCAA"),
    ("very-important-prospects", "Very Important Prospects", "VIP-", VIP,     "NCAA"),
    ("bowman-verified",     "Bowman Verified",         "BV-",  BOWMAN_VERIFIED,"NCAA"),
    ("roy-favorites",       "ROY Favorites",           "RY-",  ROY_FAVORITES,  "NBA"),
    ("hobby-stars",         "Hobby Stars",             "HS-",  HOBBY_STARS,    "NBA"),
    ("young-kings",         "Young Kings",             "YK-",  YOUNG_KINGS,    "NBA"),
    ("rockstar-rookies",    "Rockstar Rookies",        "RR-",  ROCKSTAR_ROOKIES,"NBA"),
    ("greatness-loading",   "Greatness Loading",       "GL-",  GREATNESS_LOADING,"NBA"),
]

for subset_id, name, prefix, cards, league in INSERT_SUBSET_DEFS:
    subsets.append({
        "id": subset_id,
        "name": name,
        "cardPrefix": prefix,
        "cardCount": len(cards),
        "type": "insert",
        "isAuto": False,
        "isInsert": True,
        "league": league,
        "parallels": INSERT_COMMON_PARALLELS,
        "cards": [{"number": f"{prefix}{n}", "player": p, "team": t} for n, p, t in cards],
    })

# Mega-exclusive Mojo inserts
subsets.append({
    "id": "mega-rookies",
    "name": "Mega Rookies",
    "cardPrefix": "MR-",
    "cardCount": 25,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NBA",
    "parallels": MEGA_INSERT_PARALLELS,
    "exclusive": "Mega",
    "cards": [{"number": f"MR-{n}", "player": p, "team": t} for n, p, t in MEGA_ROOKIES],
})

subsets.append({
    "id": "mega-prospects",
    "name": "Mega Prospects",
    "cardPrefix": "MP-",
    "cardCount": 25,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NCAA",
    "parallels": MEGA_INSERT_PARALLELS,
    "exclusive": "Mega",
    "cards": [{"number": f"MP-{n}", "player": p, "team": t} for n, p, t in MEGA_PROSPECTS],
})

# Spotlights
subsets.append({
    "id": "spotlights-nba",
    "name": "Bowman Spotlights — NBA",
    "cardPrefix": "BNB-",
    "cardCount": 10,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NBA",
    "parallels": ["chrome-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in SPOTLIGHTS_NBA],
})
subsets.append({
    "id": "spotlights-nil",
    "name": "Bowman Spotlights — NIL",
    "cardPrefix": "BNS-",
    "cardCount": 5,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NCAA",
    "parallels": ["chrome-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in SPOTLIGHTS_NIL],
})

# Crystallized
subsets.append({
    "id": "crystallized-nba",
    "name": "Crystallized — NBA",
    "cardPrefix": "CNB-",
    "cardCount": 10,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NBA",
    "parallels": ["crystal-gold", "crystal-orange", "crystal-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in CRYSTALLIZED_NBA],
})
subsets.append({
    "id": "crystallized-nil",
    "name": "Crystallized — NIL",
    "cardPrefix": "CNL-",
    "cardCount": 5,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NCAA",
    "parallels": ["crystal-gold", "crystal-orange", "crystal-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in CRYSTALLIZED_NIL],
})

# Anime
subsets.append({
    "id": "anime-nba",
    "name": "Anime — NBA",
    "cardCount": 25,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NBA",
    "parallels": ["chrome-black", "chrome-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in ANIME_NBA],
})
subsets.append({
    "id": "anime-nil",
    "name": "Anime — NIL",
    "cardCount": 5,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NCAA",
    "parallels": ["chrome-black", "chrome-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in ANIME_NIL],
})

# GPK
subsets.append({
    "id": "gpk-nba",
    "name": "Bowman GPK — NBA",
    "cardCount": 5,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NBA",
    "parallels": ["chrome-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in GPK_NBA],
})
subsets.append({
    "id": "gpk-nil",
    "name": "Bowman GPK — NIL",
    "cardCount": 4,
    "type": "insert",
    "isAuto": False,
    "isInsert": True,
    "league": "NCAA",
    "parallels": ["chrome-red", "chrome-superfractor"],
    "cards": [{"number": num, "player": p, "team": t} for num, p, t in GPK_NIL],
})

# ---------------------------------------------------------------------------
# Build final document
# ---------------------------------------------------------------------------

doc = {
    "set": {
        "id": "2025-26-bowman-basketball",
        "name": "2025-26 Bowman Basketball",
        "manufacturer": "Topps",
        "sport": "Basketball",
        "season": "2025-26",
        "releaseDate": "2026-04-22",
        "megaReleaseDate": "2026-05-07",
        "baseCardCount": 200,
        "prospectCardCount": 100,
        "configurations": ["Hobby", "Jumbo", "Mega", "Value", "Breaker's Delight"],
    },
    "parallelLibrary": PARALLELS,
    "subsets": subsets,
}

# Write
out_path = Path("/sessions/ecstatic-peaceful-tesla/mnt/outputs/2025-26-bowman-basketball-checklist.json")
out_path.write_text(json.dumps(doc, ensure_ascii=False, indent=2))

# Print stats
total_cards = sum(len(s["cards"]) for s in subsets)
total_variants = 0
for s in subsets:
    base_count = len(s["cards"])
    parallel_count = len(s.get("parallels", []))
    # Each card has 1 base variant + 1 variant per parallel
    total_variants += base_count * (1 + parallel_count)

print(f"Subsets: {len(subsets)}")
print(f"Unique cards: {total_cards}")
print(f"Total trackable variants (card x parallel): {total_variants:,}")
print(f"Output: {out_path}")
print(f"Size: {out_path.stat().st_size / 1024:.1f} KB")
